lookit/lookit-api

- exp/urls.py
- web/templates/web/_navigation.html
- Redirect `/exp/` to `/exp/studies/`
> Add conditional nav to lookit

- .dockerignore
- Dockerfile
- manage.py
- project/wsgi.py
- requirements/defaults.txt
> Add docker, update wsgi & requirements to match

- project/settings/defaults.py
- project/settings/local-dist.py
- setup.cfg
- studies/helpers.py
- studies/models.py
- studies/templates/emails/notify_admins_of_study_action.html
- studies/templates/emails/notify_admins_of_study_action.txt
- studies/templates/emails/notify_researchers_of_approval_decision.html
- studies/templates/emails/notify_researchers_of_approval_decision.txt
- studies/templates/emails/notify_researchers_of_approval_rescission.html
- studies/templates/emails/notify_researchers_of_approval_rescission.txt
- studies/workflow.py
Add email support
[[LEI-427]](https://openscience.atlassian.net/browse/LEI-427)
> [Feature] Email with Sendgrid [LEI-427]

- exp/mixins/participant_mixin.py
- exp/views/study.py
- studies/models.py
- studies/templates/studies/study_edit.html
- studies/templates/studies/study_json.html
- studies/templates/studies/study_responses.html
- web/templates/flatpages/default.html
https://openscience.atlassian.net/browse/LEI-429
1. Allow researcher to toggle between JSON/CSV display of individual and all responses.
2. Allow researcher to download individual responses/all responses as JSON or CSV.
3.  If certain study fields are edited after the study has been approved, force the study back into the "rejected" state, and leave comments explaining why.  User must resubmit for the study to be approved again.
** Note, I am giving the action a log - when it is moved back to rejected, but which user to attach to this log?  I attached the study's creator, but a system user or no log would make sense to me too.
> [WIP] Feature/Download CSV and Force Resubmission of Study if Edited[LEI-429]

- accounts/templates/accounts/participant_detail.html
- accounts/templates/accounts/participant_list.html
- accounts/templates/accounts/researcher_list.html
- exp/views/study.py
- studies/templates/studies/study_edit.html
- studies/templates/studies/study_list.html
Tickets
https://openscience.atlassian.net/browse/LEI-442
QA Finds
> Feature/Cleanup #4 [LEI-442]

- accounts/templates/emails/notify_researcher_of_org_permissions.html
- accounts/templates/emails/notify_researcher_of_study_permissions.html
- accounts/templates/emails/resend_confirmation.html
- accounts/templates/emails/resend_confirmation.txt
- accounts/templates/emails/reset_password.html
- accounts/templates/emails/reset_password.txt
- project/settings/defaults.py
- studies/templates/emails/notify_admins_of_study_action.html
- studies/templates/emails/notify_researchers_of_approval_decision.html
- studies/templates/studies/study_attachments.html
- studies/templates/studies/study_form.html
- studies/templates/studies/study_responses.html
- web/templates/web/study-detail.html
- web/views.py
> Feature/Lookit Cleanup 9

- project/settings/defaults.py
- requirements/defaults.txt
> Add django celery beat and make celery beat the default scheduler

- web/templates/web/studies-history.html
Fix reference to study's image url so image will show up on past studies page.
> Feature/Study Image on Past Studies Page

- docs/source/django-project-installation.md
- docs/source/ember-app-installation.md
- docs/source/index.rst
- docs/source/local-frame-development.md
Add docs that explain how to get the whole setup running locally so you can make changes to frames and test them in your local environment.
> Feature/Add Documentation for local development of frames

- accounts/scripts/import_jamdb_participants.py
Fix lookit_referrer and additional_information fields in participant migration.
> Feature/Fix Migration

- attachment_helpers.py
- exp/mixins/study_responses_mixin.py
- exp/views/study.py
- project/settings/defaults.py
- requirements/defaults.txt
- studies/tasks.py
- studies/templates/emails/download_zip.html
- studies/templates/emails/download_zip.txt
- Requesting to download multiple attachments starts a celery task that generates a zip file, uploads it to google cloud storage, creates a signed url, and emails it to the requesting user.
- If a zip file with the same videos already exists on google cloud storage it just generates the link and emails it.
> Move bulk video downloads to a celery task

- osf_oauth2_adapter/admin.py
https://openscience.atlassian.net/browse/LEI-473
> Feature/Remove Social Account from Admin App [LEI-473]

- project/settings/defaults.py
- studies/tasks.py
Allow for configurable repo url and branch.
> [feature] repo settings

- docs/source/local-frame-development.md
- web/templates/web/studies-history.html
- web/templates/web/studies-list.html
Minor change to display eligibility criteria on study thumbnails and to add a warning about mobile devices to the study list page as a quick stopgap measure, as many parents are trying to participate on mobile devices. 
(I've made a separate branch, current-docs, to target minor updates to the documentation going forward - that way they get served right away without constant redeployments of the staging server. Sorry about that!)
> Update formatting of study list page

- ember_build/build.sh
> Trying to trigger Travis CI

- studies/tasks.py
> Trying to get around the docker permissions bug

- ember_build/Dockerfile
- studies/tasks.py
Cheating the layering system and doing some dirty hacks to get the final build size down.
> Vastly improved dockerfile

- ember_build/Dockerfile
Just getting rid of the extra garbage layer that we introduced in order to cache-bust.
> Getting rid of garbage layer

- studies/tasks.py
Per https://github.com/googleapis/google-cloud-python/issues/3139
```
@arvindnrbt with consulting hat on "It depends...". You could:
Iterate and upload files one by one.
Populate a queue.Queue with the filenames and have worker threads upload items from the queue.
Populate a cross-process queue and have worker processes upload items from the queue.
You can't:
Upload a zipfile and have GCS automagically explode its entries into blobs / objects.
Create a "batched" MIME request and do multiple uploads in a single request.
```
> giving up on this, sadly

- ember_build/Dockerfile
Tested this locally - it should work the same in staging
> Global Bower to make experiment builds more robust

- project/settings/defaults.py
> Fixing the paths

- studies/templates/emails/notify_admins_of_study_action.html
- studies/templates/emails/notify_admins_of_study_action.txt
- studies/templates/emails/notify_researchers_of_deployment.html
- studies/templates/emails/notify_researchers_of_deployment.txt
> Corrected links

- requirements/defaults.txt
Looks like a successful travis build. This should fix #215
> let\'s see this build successfully in staging

- project/settings/defaults.py
- requirements/defaults.txt
Let's hope this does the trick...
> Unfortunately, will have to test the downgrade in staging

- studies/tasks.py
> Always pin the commit sha of the dependency being used

- ember_build/Dockerfile
- ember_build/build.sh
- studies/tasks.py
This will fix #220 in staging.
> Move back to old build style to use pipe env vars

- exp/views/study.py
- studies/forms.py
- studies/templates/studies/study_detail.html
- studies/templates/studies/study_edit.html
- studies/workflow.py
Upon review of #228 : one typo fix, several aesthetic changes for study detail view while I was looking at it anyway, consolidation of study forms mostly for reuse of help text.
> 208 ui improvements study edit kim review

- exp/views/study.py
- studies/models.py
- studies/tasks.py
Just going to create this PR without testing too much - I'm fairly certain that these changes will fix our problems
> Fixes #244, Fixes #245, and #247

- studies/models.py
- studies/tasks.py
> do not invalidate build prematurely

- exp/views/study.py
Using proper subqueries instead of that LEFT OUTER JOIN garbage
> query is much faster now

- exp/views/study.py
- studies/migrations/0043_add_video_constructs.py
using subqueries instead of a count on a left outer join
> Merge study list query optimization code

- accounts/templates/account/login.html
- exp/mixins/study_responses_mixin.py
- exp/static/exp/css/app.css
- exp/views/study.py
- studies/models.py
- studies/serializers.py
- studies/templates/studies/study_responses_consent_ruling.html
Available to view at ngrok hook
> Adding withdrawal info to consent manager

- exp/static/exp/css/app.css
- studies/templates/studies/study_participant_contact.html
As well as some helpful comments
> Patch up XSS vulnerability and clean up little ui details

- studies/templates/studies/study_participant_contact.html
Should have done this earlier.
> date filter component to reflect initial query state

- studies/templates/studies/study_participant_contact.html
Keeping source for original select handler commented in case we want to revert to the old behavior
> message open only on double click

- Pipfile
- Pipfile.lock
- exp/views/study.py
- project/settings/defaults.py
- requirements/defaults.txt
We will move pyinstrument outside of requirements.txt and add it to MIDDLEWARE in the proper DEBUG=True block of django's default settings after I'm done debugging this. Right now I just need to understand why there's such a big delta between local, prod, and staging
> adding profiling and merging to staging

- project/settings/defaults.py
- requirements/defaults.txt
Looks like it was the select_related for responses that I removed in the previous PR - WOW that was a huge performance impact for large sets of responses!
> Debugging complete, source of slowness found

- attachment_helpers.py
will take off about 1/2 time per response fetched
> Move s4 client creation out to global module level

- api/views.py
PR to dev to test on staging, but should also deploy to prod so we can use preview there.
> fix preview view

- exp/static/exp/css/app.css
- studies/fields.py
- studies/templates/studies/study_participant_eligibility.html
> Requested Changes to Age Range Sliders

- accounts/admin.py
- api/views.py
- studies/templates/studies/study_detail.html
This finalizes the changes for #141
> Add navigation to eligibility form

- attachment_helpers.py
- web/templates/web/studies-history.html
- web/views.py
> Study History contains downloadable session videos

- web/views.py
I'm not actually sure if this is going to fix things because I don't
actually record myself dictating the consent text. But the reverse
ordering shows pretty consistent frames in terms of what I hear in the
background soooo I'm pretty sure this is gonna work.
> Attempt to fix video ordering

- accounts/queries.py
> Allow empty expressions

- web/templates/web/studies-history.html
Fixing the markup so that videos can be downloaded again
> Merge develop

- exp/views/study.py
- studies/fields.py
This provides for a noticeable decrease in latency during query time,
and has the added benefit of reducing object overhead since we're not
serializing full-blown django models.
> Using .values() to constrict queryset

- exp/views/study.py
- studies/fields.py
- studies/templates/studies/study_participant_analytics.html
Attempting to follow some advice here: https://github.com/metricsgraphics/metrics-graphics/issues/563 and here: https://github.com/metricsgraphics/metrics-graphics/issues/661
Let's see if this works!
> Attempt to fix browser memory issues

- studies/templates/studies/study_participant_analytics.html
This shouldn't have much of an affect on staging data, but we'll see.
> remove interpolation in binned registration plots

- exp/views/study.py
- studies/templates/studies/study_participant_analytics.html
To solve the memory problems - instead of generating null datapoints, we specify the number of bins going into the binned histograms upfront and let MetricsGraphics do the hard work of displaying the data correctly.
> Different approach to null point handling

- studies/templates/studies/study_participant_analytics.html
Fixing registration graph bins
> Merge develop to master

- exp/views/study.py
- studies/queries.py
- studies/templates/studies/study_responses_consent_ruling.html
This also requires us to issue a separate query for summary stats.
> Exclude responses w/ approvals older than 3 weeks

- exp/views/study.py
- studies/models.py
- studies/queries.py
- studies/templates/studies/study_responses_consent_ruling.html
This should alleviate #380 , though I won't say "fixes" yet as that will trigger the automation to close the issue :)
> Reduce exp_data instances in Consent Manager

- exp/views/study.py
This should have a reasonably salient effect in prod.
> Override bad queryset from StudyResponsesMixin

- accounts/templates/accounts/participant_detail.html
- api/views.py
- exp/static/exp/css/app.css
- exp/templates/exp/_navigation.html
- exp/views/study.py
- exp/views/user.py
- studies/queries.py
- studies/templates/studies/_response_nav_tabs.html
- studies/templates/studies/study_attachments.html
- studies/templates/studies/study_detail.html
- studies/templates/studies/study_responses.html
- studies/templates/studies/study_responses_consent_ruling.html
perhaps a bit overdue - this will fix #395 among others.
> Merge develop into master

- accounts/models.py
- api/views.py
- exp/mixins/study_responses_mixin.py
- exp/static/exp/css/app.css
- exp/urls.py
- exp/views/study.py
- studies/templates/studies/_all_json_and_csv_data.html
- studies/templates/studies/study_responses.html
Downloadable CSV data was previously largely unusable for analysis (i.e. contained large chunks of JSON so you needed to process the JSON regardless). Has been split into an overview with one line per response + a detailed file with data in a fairly standard 'long' format, both with data dictionaries / dictionary templates! Addresses #148 and forms a foundation for #321 coming next.
> 148: Improve CSV data

- exp/views/study.py
- studies/tasks.py
Fixes to make the file downloads not run out of memory or time out are finally working & ready for review! 
QUESTION: do we need to be cleaning up video archives and frame data dict files that get put in blobs on GCP, like we do with the docker containers & checkouts?
> minor cleanup mostly to make a PR for review

- exp/views/study.py
This was a pretty rushed fix - hoping @kimberscott can come in and clean up and take the baton the last mile.
TODO:
1) pull out the actual fields needed instead of using `**recipient.__dict__`
2) commit in terms of design - `participant_slug_from_model` or `participant_slug` should be used, contingent on the query set construction. If you use .values() (generally the right way to do it), you lose the convenience of model methods but save memory (and request time) by not serializing huge python objects.
> Sort of hacky fix to get the query fast again

- attachment_helpers.py
- studies/helpers.py
Finishes out changes for this bug fix. Should also merge into master right away to avoid further apparently-missing data.
> clean up old consent save hook and old consent video collector

- .travis.yml
Hopefully we can just have Travis manage PG!
> Fixing travis builds for non-production pipeline branch commits

- cloudbuild.yaml
Addresses #466 and fixes problem introduced in #467
> Fix keyring location

- cloudbuild.yaml
Addresses #466 and fixes problem introduced in #467
> Ensure VERSION variable interpolated correctly

- .isort.cfg
- .pre-commit-config.yaml
What a happy surprise! Getting rid of `allauth` makes precommit happy.
> :bug: See if seed-isort-config complains

- studies/tasks.py
- studies/tests.py
> :bug: Deleted children excluded from target query

- accounts/forms.py
- accounts/models.py
- accounts/tests.py
> Allow case-insensitive login

- accounts/tests.py
- exp/tests/test_contact_views.py
- exp/views/contact.py
- exp/views/user.py
* Add contact view tests
* Limit recipients to study participants (beyond limiting options in UI)
* Test requirement for 2fa login on ALL exp views
* Use ExperimenterLoginRequiredMixin on ParticipantDetailView for consistency
> Bugfix/546 message participants fix - add tests!

- requirements/release.txt
> Pin gevent and greenlet

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/scoping.md
- CONTRIBUTING.md
> CONTRIBUTING.md

- CONTRIBUTING.md
- project/settings.py
- project/urls.py
- web/views.py
- Changing the invoke task reference to invoke new-version
- black fixes
> Doc fixes and linter warnings

- accounts/models.py
To address #588, would just like to confirm on staging that this is a fix
> quick initial fix for bulk email

- ember_build/Dockerfile
this seems to "just work" locally; I'd like to test on staging to make sure builds succeed using commits people are using on prod.
> use node 10 for experiment runner builds

- project/sendgrid_backend.py
> fix for larger images not being sent due to incorrect encoding

- studies/templates/studies/_study_fields.html
& remove (s) from year/month/day labels for readability. Completes implementation (but not tests) of #609
> update min/max age in days upon page load as well as upon value change

- exp/views/lab.py
- studies/helpers.py
- studies/models.py
- studies/tasks.py
- studies/tests.py
I have added reply-to email addresses on lab and study submission emails.
> [Bug fix/661] Add reply-to email address

- Dockerfile
- poetry.lock
- pyproject.toml
- tasks.py
Inside the, now removed, requirements directory there were some additional packages (including the `gevent` package that we saw in an error).  They've now been added to the `pypackage.toml` and lock files.
> Found some required packages in requirements dir

- tasks.py
Forgot to install the pre-commit hook (again!!!), therefore I've added it to the setup task within invoke.
> Add pre-commit install to invoke setup task

- exp/templates/exp/base.html
- web/templates/403.html
- web/templates/flatpages/default.html
- web/templates/web/base.html
- web/templatetags/web_extras.py
Add google analytics to every page.  I used the code from [this page](https://analytics.google.com/analytics/web/?authuser=1#/a163886699w229379580p216075426/admin/tracking/tracking-code/).  
Note:  The dashboard isn't setup.  I think there needs to be data collected by GA first to setup the filters.
> Add google analytics

- .travis.yml
The credentials for docker username and password are in the travis environment variables within their console.
> Update to travis config to login to docker

- .isort.cfg
- .travis.yml
- exp/tests/test_study_views.py
- exp/views/study.py
- poetry.lock
- pyproject.toml
- studies/models.py
- studies/templates/emails/notify_researchers_of_approval_decision.html
- studies/templates/emails/notify_researchers_of_approval_decision.txt
- studies/templates/studies/study_detail.html
- studies/workflow.py
- travis.Dockerfile
Add textbox to study acceptance model. When comments are left, they are displayed in the comments box and logged.
Closes #610
> Added acceptance comment box

- env_dist
- exp/templates/exp/base.html
- web/templates/403.html
- web/templates/flatpages/default.html
- web/templates/web/base.html
- web/templatetags/web_extras.py
This PR adds the correct Google Tag Manager code to our HTML templates.
> Google Tag Manager

- studies/templates/studies/study_responses_consent_ruling.html
Update error message when video doesn't load. 
Closes #262
> Update message when video doesn't load

- poetry.lock
Update python libraries were available and not pinned.
> Keeping packages up to date

- Dockerfile
This is a stopgap solution to getting the studies list feature onto staging.
> Stopgap solution to staging deploy 

- Dockerfile
The same stopgap solution, but with graphviz libraries.
> Stopgap staging deploy

- web/static/base.css
- web/templates/web/studies-list.html
This is to move the "log in message" to the search bar.
> Move log in message to search bar

- Dockerfile
- cloudbuild.yaml
- dev.Dockerfile
Here is my latest attempt at getting two docker images:
- One image for running tests
- A second image for for pushing to GCR and running in production.
> Install dev dependencies only for tests

- cloudbuild.yaml
Id field must be unique for the test image.  This builds of the previous PR #763.
> Id field must be unique under steps

- accounts/forms.py
- tasks.py
- web/tests.py
- web/views.py
This PR adds validation to the search bar form.  This should prevent the error recorded in sentry here:
https://sentry.io/organizations/massachusetts-institute-of-technology/issues/2537850350/?environment=production&project=299962&referrer=alert_email
> Add form validation to the search bar.

- .travis.yml
- accounts/forms.py
- web/templates/web/studies-list.html
- web/templatetags/web_extras.py
- web/tests/test_external_views.py
- web/tests/test_views.py
- web/views.py
This is an update to the search bar for the Studies List view.  This closes #785.
> Update studies list view search bar

- studies/models.py
- studies/tests.py
This PR will contain additional test cases as well as fixes from initial QA of staging.
> Updates for external studies

- studies/tests.py
As the subject states, move the external email test case into the appropriate class for email test cases.
> Move external email test case

- exp/templates/exp/_navigation.html
- exp/templates/exp/base.html
- poetry.lock
- pyproject.toml
- studies/templates/studies/study_detail.html
- studies/templates/studies/study_edit.html
- studies/templates/studies/study_participant_analytics.html
- studies/templates/studies/study_participant_contact.html
- studies/templates/studies/study_participant_eligibility.html
- web/templates/flatpages/default.html
- web/templates/web/base.html
- web/views.py
This PR covers two main issues:
- Fix arrow icons
- Security fix
> Deploy changes to master

- exp/templates/exp/support.html
Updates to the `Support Lookit` page.
> Updates to the support lookit page

- exp/templates/exp/_navigation.html
- exp/templates/exp/support.html
- exp/tests/test_study_views.py
- exp/urls.py
- exp/views/__init__.py
- exp/views/mixins.py
- exp/views/study.py
- exp/views/support.py
- studies/forms.py
- studies/templates/studies/_study_fields.html
This PR is to deploy recent PRs into production.
> Deploy to production

- studies/templates/studies/study_attachments.html
- studies/templates/studies/study_participant_analytics.html
This PR fixes the following sonarcloud issues:
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8kd8RosUr7kBuIq5u&open=AXy8kd8RosUr7kBuIq5u
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8kd8YosUr7kBuIq54&open=AXy8kd8YosUr7kBuIq54
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8kd8YosUr7kBuIq55&open=AXy8kd8YosUr7kBuIq55
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8kd8YosUr7kBuIq57&open=AXy8kd8YosUr7kBuIq57
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8kd8YosUr7kBuIq58&open=AXy8kd8YosUr7kBuIq58
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8kd8YosUr7kBuIq5-&open=AXy8kd8YosUr7kBuIq5-
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AX …
> Html fixes

- exp/static/exp/css/bootstrap-editable.css
This PR resolves sonarcloud issues:
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq72&open=AXy8keBlosUr7kBuIq72
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq73&open=AXy8keBlosUr7kBuIq73
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq74&open=AXy8keBlosUr7kBuIq74
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq75&open=AXy8keBlosUr7kBuIq75
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq76&open=AXy8keBlosUr7kBuIq76
> Fixing css for linear-gradient

- exp/static/exp/css/app.css
- exp/static/exp/css/bootstrap-editable.css
This resolves the following sonarcloud issues:
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBeosUr7kBuIq7s&open=AXy8keBeosUr7kBuIq7s
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBeosUr7kBuIq7t&open=AXy8keBeosUr7kBuIq7t
Additionally, this addresses the following bugs from sonarcloud:
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq7u&open=AXy8keBlosUr7kBuIq7u
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq7v&open=AXy8keBlosUr7kBuIq7v
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq7w&open=AXy8keBlosUr7kBuIq7w
- https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8keBlosUr7kBuIq7x&open=AXy8keBlosUr7kBuIq7x
- …
> Addressing css issues reported by sonarcloud

- exp/tests/test_study_forms.py
- studies/migrations/0066_new-lab-study-perms-data-migration.py
This resolves a couple sonarcloud issues:
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8keAZosUr7kBuIq7V
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8keAZosUr7kBuIq7W
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8kd2CosUr7kBuIq4h
> Update hardcoded urls to use ssl/tls

- dev.Dockerfile
Fixed issues with the dev docker file that arose from PR #898.
> Update dev dockerfile for changes with poetry

- accounts/templates/accounts/participant_detail.html
Replace `<b>` tags with `<strong>` tags.  
This issue was reported many times by sonarcloud all were very much like the following: https://sonarcloud.io/project/issues?id=lookit_lookit-api&issues=AXy8kd0xosUr7kBuIq31&open=AXy8kd0xosUr7kBuIq31
> Update b tag

- web/templates/web/demographic-data-update.html
Removed h1 tag wrapping paragraph.  Additionally, removed div tag as it wasn't necessary.  
Closes #724
> Remove h1 tag from text

- web/templates/frontpages/resources.html
Removed the JS call that converts the select list to a searchable drop down.  
Closes #720
> Removed search dropdown from state selector

- web/static/base.css
- web/templates/web/study-detail.html
Added h3 to section headings.  Additionally, updated the heading tag for "Would you like to participate in this study?".
Closes #725
> Added heading tag to study detail page

- exp/static/exp/css/app.css
- poetry.lock
- project/settings.py
- project/urls.py
- pyproject.toml
- web/static/base.css
Adjust colors on the main pages to reflect WCAG AA standards.  Some of the changes to the main pages made sense to move to the experimenter pages as well.  The experimenter pages were _not_ thoroughly combed through.  
Closed #706
> Color contrast

- web/templates/web/participant-signup.html
Update create account copy to make it more readable.  Change request is from [this comment](https://github.com/lookit/lookit-api/pull/926#pullrequestreview-903211816).
> Update create account copy

- exp/static/exp/css/app.css
- exp/templates/exp/support.html
- poetry.lock
- project/settings.py
- project/urls.py
- pyproject.toml
- studies/templates/studies/_image_display.html
- studies/templates/studies/study_detail.html
- web/static/base.css
- web/templates/frontpages/default.html
- web/templates/frontpages/faq.html
- web/templates/frontpages/resources.html
- web/templates/frontpages/scientists.html
- web/templates/web/demographic-data-update.html
- web/templates/web/participant-signup.html
- web/templates/web/studies-list.html
- web/templates/web/study-detail.html
Moving a few fixes into Production:
1. Researcher registration link should be more visible
2. General accessibility updates
> Move Staging into Production

- exp/tests/test_study_views.py
- web/templates/web/study-detail.html
Update the study details page to reflect changes for CHS merger.
Closes  #921
> Study details redesign

- .travis.yml
- web/static/base.css
- web/templates/web/studies-list.html
- web/tests/test_views.py
- web/views.py
Update study list cards to reflect CHS changes. 
Closes #920
> Update for study list cards

- web/static/base.css
- web/templates/web/_navigation.html
- web/templates/web/study-detail.html
- web/templatetags/web_extras.py
Update login so that the current page is stored in the query string.
Login from study's detail page:
Login from navigation bar:
> Fix login next

- .pre-commit-config.yaml
- poetry.lock
- project/settings.py
- pyproject.toml
- studies/fields.py
- tasks.py
Add command to create entry in site database table during local environment setup. 
The Python package `Black` was updated as the pinned version was broken.
> Add command to create site for local dev env

- accounts/views.py
A bug was found where users that require 2fa to gain access aren't being redirected to their original view.  This PR is to cover this bug.  This update will how user's are redirected after login.
> Add next to url on 2fa

- accounts/forms.py
- accounts/scripts/import_jamdb_participants.py
- accounts/serializers.py
- accounts/templates/accounts/participant_detail.html
- exp/views/analytics.py
- exp/views/responses.py
- exp/views/responses_data.py
- web/static/js/demographics-form.js
- web/templates/web/child-add.html
- web/templates/web/child-update.html
- web/templates/web/demographic-data-update.html
This PR is to add the necessary JavaScript to control the conditional fields in the demographics forms.
> Update demo js

- accounts/templates/accounts/participant_list.html
- exp/views/responses.py
- studies/templates/studies/lab_list.html
- studies/templates/studies/lab_member_list.html
- studies/templates/studies/study_attachments.html
- studies/templates/studies/study_list.html
Fixes 500 error found when searching in response video view.
Closes #1007
> Response video search error

- exp/views/study.py
This adds declaration to the comments box in the study details page. 
Closes #1009
> Declarations in study comments

- accounts/forms.py
This is to get the copy change on the demo form into production.
> Move develop into master

- web/templates/frontpages/default.html
Update funding blurb.  I new new grant number was added to the list. 
Closes #1022
> Update funding blurb

- accounts/templates/accounts/participant_list.html
- exp/views/user.py
On experiment participant's page, filter by participant's UUID as well as their nickname. 
Closes #919
> Filter participants by uuid as well as nickname

- studies/fields.py
This add Hebrew to the list of languages for a child. 
Closes #1052
> Add hewbrew to languages

- studies/forms.py
- studies/templates/studies/lab_create.html
On reviewing the changes to the lab form, found that the new images weren't in the new lab form.  This PR should clean up the lab form code and resolve this issue.
> Lab images new lab

- project/settings.py
- web/templatetags/web_extras.py
Update to google manager tag code.
> Update google tag code

- studies/templates/studies/_study_fields.html
Move a few features into production.
> Move Feature in to production

- accounts/forms.py
This PR updates the ethnicity label.
> Update ethnicity label

- web/templates/web/base.html
- web/templates/web/static.html
This PR will handle the changes to the login view.  
In addition to the login view, there will be changes to the home and the 2FA login views.
> Bootstrap 5 Login view

- accounts/templates/accounts/participant_detail.html
Updates to the Participant Details view.
> Bootstrap 5 exp participant detail

- studies/static/studies/js/study-detail.js
- studies/static/studies/js/study-responses-consent-ruling.js
- studies/templates/studies/study_responses_consent_ruling.html
This the BS5 update for the consent judgment view.
> Bootstrap 5 exp responses consent ruling

- accounts/templates/accounts/2fa-setup.html
- web/static/css/2fa-setup.css
BS5 changes for the 2fa set up page.
> Bootstrap 5 2FA setup

- scss/custom.scss
- web/static/custom_bootstrap5.css
This PR will make link colors darker for readability.
> Make link colors darker

- accounts/templates/accounts/2fa-setup.html
- accounts/templates/accounts/account-update.html
- accounts/templates/accounts/researcher-registration.html
- studies/templates/studies/lab_create.html
- studies/templates/studies/lab_update.html
- studies/templates/studies/study_participant_contact.html
- web/templates/registration/login.html
- web/templates/registration/password_reset_complete.html
- web/templates/registration/password_reset_confirm.html
- web/templates/registration/password_reset_done.html
- web/templates/registration/password_reset_form.html
- web/templates/web/child-add.html
- web/templates/web/child-update.html
- web/templates/web/demographic-data-update.html
- web/templates/web/participant-email-preferences.html
- web/templates/web/participant-signup.html
This PR is to fix the (Overlooked) registration views.
> Fix registration views

- web/static/js/study-participant-contact.js
This PR will fix issues with displaying recently sent emails.
> Add time to date picker filter

- studies/templates/studies/lab_detail.html
On local (Staging) data, there was a template error were a variable wasn't set.  After making sure value was set, errors seem to be fixed. 
Closes #1163
> Found error where variable wasn't set

- scss/base.scss
- scss/custom-maps.scss
- scss/custom-variables.scss
- web/static/custom_bootstrap5.css
- web/templates/web/home.html
Add appropriate sass to add red theme to our css.  Add new "text-red" class to icons on home page.
> Change the icons on the home page to red

- poetry.lock
- project/settings.py
- pyproject.toml
the `django-allauth` package has the dependency of the `oauthlib` which dependabot is wanting to update due to security issues.  These libraries aren't being used.
> Remove unnecessary allauth package

- accounts/templates/accounts/participant_detail.html
- scss/base.scss
- studies/templates/studies/lab_list.html
- studies/templates/studies/lab_member_list.html
- studies/templates/studies/study_attachments.html
- studies/templates/studies/study_list.html
- studies/templates/studies/study_responses.html
- web/static/custom_bootstrap5.css
- web/templates/web/studies-history.html
- web/templates/web/studies-list.html
- web/templatetags/web_extras.py
Replace template function for sass class that extends BS5 classes that were used to style empty text.
> Replace template function with new css class

- studies/templates/studies/study_responses.html
- studies/templates/studies/study_responses_consent_ruling.html
Fixes #615 
@mekline my drafts of the help text and associated screenshots are on [this comment](https://github.com/lookit/lookit-api/issues/615#issuecomment-1505898006) in #615. Could you let me know if you'd like any changes to the text? Thanks!
> Help text for consent notes and response feedback - fixes #615

- studies/fields.py
Update the language label for two Chinese languages. 
Closes #1135
> Update chinese language label

- web/urls.py
- web/views.py
Here are the new age grouped filters for the study list view.
> Add age filters

- web/templates/registration/login.html
- web/templates/web/participant-signup.html
- Sign up page: "Ready to participate in a Lookit study?" --> "Ready to participate in a study with Children Helping Science?"
- Log in page: "New to Lookit?" --> "New to Children Helping Science?"
> Changes to sign up and login pages for CHS merger

- studies/templates/studies/study_detail.html
- studies/templates/studies/study_detail/_modal.html
- studies/workflow.py
- web/static/js/study-detail.js
Update modal for study submit. 
Closes #1201
Internal Study:
External Study:
> Changes to submit modal text

- Makefile
- web/static/js/study-detail.js
This PR is to get a bug fix into production.
> Move bug fix into production

- exp/views/study.py
This PR is a result of researching into why the studies view might be loading slowly.  This outcome of this research can be found in the issue #1256.  
For this PR, a couple of things where addressed. 
1. There were values that where generated twice.  This duplication was removed by attributing these value to a variable.  
2. Updating a dictionary can be done [more efficiently](https://stackoverflow.com/a/31928523) by using the `update()` method.  
Generally, the outcome of this PR probably won't have much effect on the user, but it seemed like a waste to not have these code changes at least reviewed.
> Refactored study context

- studies/templates/studies/study_participant_analytics.html
- web/templates/registration/password_change_form.html
Here's a fix to some security issues sonarcloud found.  This PR is going to cover the found bugs and the code smells will have to be addressed another time.
> Sonarlint security issues

- accounts/views.py
Closes #987
Updates success message when user changes their account information.
> Banner message when updating account information

- exp/templates/exp/_navigation.html
- web/templates/web/_navigation.html
- web/templates/web/garden/_navigation.html
Closes #1226
Some more copy changes for the GARDEN Project.
> Project garden subsite requested changes

- exp/tests/test_runner_forms.py
- exp/views/study.py
- project/settings.py
- studies/forms.py
- studies/templates/studies/experiment_runner/efp_edit.html
- web/static/js/efp-runner.js
This moves a couple fixes in to production.
- #1276 
- #1277
- #1279
> Move updates to production

- pyproject.toml
This PR adds an author to the Lookit project.  It's was updated to `lookit <lookit@mit.edu>`.
> Add lookit as the project author

- accounts/templates/accounts/participant_detail.html
- studies/templates/studies/_all_json_and_csv_data.html
- studies/templates/studies/experiment_runner/base.html
- studies/templates/studies/experiment_runner/efp_edit.html
- studies/templates/studies/lab_create.html
- studies/templates/studies/lab_detail.html
- studies/templates/studies/lab_member_list.html
- studies/templates/studies/lab_update.html
- studies/templates/studies/study_attachments.html
- studies/templates/studies/study_create.html
- studies/templates/studies/study_detail.html
- studies/templates/studies/study_edit.html
- studies/templates/studies/study_participant_contact.html
- studies/templates/studies/study_responses.html
- studies/templates/studies/study_responses_consent_ruling.html
- web/static/js/efp-runner.js
- web/templatetags/web_extras.py
Moving to two PRs to production to solve two major bugs. 
1. https://github.com/lookit/lookit-api/pull/1318
2. https://github.com/lookit/lookit-api/pull/1319
> Moving a couple bug fixes to production. 

- locale/ja/LC_MESSAGES/django.po
- web/templates/web/children-list.html
Not all that big of a deal, but a fix for a few linting errors that are on develop.
> Fix linting issues

- locale/ja/LC_MESSAGES/django.po
- web/templates/web/home.html
- web/templates/web/resources.html
- web/templates/web/studies-list.html
Further small pieces of internationalisation and Japanese translation.
> internationalisation and Japanese translations

- api/views.py
- web/templates/web/faq.html
- web/templates/web/jspsych-study-detail.html
- web/urls.py
- web/views.py
Here's a bit of cleanup that will be required from changes in our jsPysch plugins mono repo.  
Also, there were a few linting errors introduced by merging in MBAH changes.
> Support current jsPsych changes 

- web/views.py
[Sentry Issue](https://massachusetts-institute-of-technology.sentry.io/issues/5188952165/events/10bba23b10c34d469f959de71ff947c3/)
When a user who no longer exists clicks on their unsubscribe link, a user "DoesNotExists" error will be recorded.  This PR handles that case.
> Sentry: User.DoesNotExist  /account/{username}/{token}/

- poetry.lock
- project/settings.py
- studies/models.py
- studies/tasks.py
- studies/tests.py
- web/urls.py
This PR will move any changes on staging to production.  Here's a list of the PRs going into production.
- #1432 
- #1433
- #1426
> Move code from develop to master

- accounts/queries.py
Antidotally, the participation eligibility function was running slowly.  This PR combines some queries within this function so that there are fewer calls to the database.
> Update child participation eligibility

- .gitignore
- .pre-commit-config.yaml
- Makefile
- exp/tests/test_response_postsave.py
- poetry.lock
- pyproject.toml
- studies/helpers.py
- studies/models.py
- web/templates/web/jspsych-study-detail.html
- web/views.py
For the experiment data coming out of jsPsych, we needed to update how the data was parsed.  This included adding a couple of conditionals and a shim until we can complete other issues.  
- Added parsing logic to exit frame property function
- For the time being, we'll not get consented responses.  This will be reverted when the consent view has been updated.
- Handle jsPsych videos on save
This isn't the full solution to the researcher's data view.  Instead, this was a good place to check in before doing more work.
> Jspsych response helpers

- .gitignore
- web/templates/web/jspsych-study-detail.html
> Update jspsych unpkg packages

- web/templates/web/jspsych-study-detail.html
Update existing packages and add jsPsych's plugins `plugin-image-button-response` and `plugin-html-button-response`.
> Update jspsych deps

- studies/forms.py
A simple change to deploy jsPsych to those who don't have superuser permissions.
> Deploy jsPsych to Production

- web/templates/web/jspsych-study-detail.html
This PR just bumps the lookit-jspsych `surveys` package version, which contains a bug fix.
> Update lookit-jspsych `surveys` package version

- Dockerfile
- Dockerfile.web
- Makefile
- studies/templates/studies/study_attachments.html
This production push is just the removal of the batch video download feature from #1491.
> Push Develop to Production

- web/static/js/study-responses.js
Add show/hide columns to IR table.
https://github.com/user-attachments/assets/9e528486-e100-4d59-ba26-4de7c109c2e7
> Add show/hide columns functionality

- web/static/js/study-responses.js
The date column looks better when the date and time are on different lines.
> Format date column

- studies/templates/studies/study_responses.html
Add class to drop-downs to match Bootstrap style.
> Add class to style dropdowns

- studies/templates/studies/study_responses.html
- web/static/js/study-responses.js
- web/templates/web/base.html
In an attempt to facilitate filter/sort on drop down values, we've decided to update Datatables to v2.  Per the documentation, we should be able to use a function to produce the values to filter or sort by.  Please see the "input" parameter in the [Datatables "column().sort()" documentation](https://datatables.net/reference/api/column().search()) for more information.
> Datatables v2

- studies/templates/studies/study_responses.html
- web/static/js/study-responses.js
This adds column filter/sort (and in some cases general filters) for Frame Exit, Payment, and Session Status columns.  
https://github.com/user-attachments/assets/676100d6-b350-49c4-bbb9-7deccd7dc408
> Ir table col filters

- studies/templates/studies/study_responses.html
- web/static/js/study-responses.js
Implement sorting on the star column.
https://github.com/user-attachments/assets/16626c8e-e7cf-49bd-9b64-70d47f0f99bc
> Implement sorting on star column

- project/settings.py
- project/storages.py
- project/urls.py
- scss/study-responses.scss
- scss/superuser.scss
- web/static/custom_bootstrap5.css
- web/templates/web/base.html
Here's another attempt to get hashed static file names working on staging.
> Hashed static files

- docker-compose.yml
This PR updates Postgres to 17.2 for our local environment.
> Update local environment to use Postgres 17.2

- cloudbuild.yaml
> Postgres Upgrade

- project/settings.py
This is a temporary change to get DEBUG working on staging.
> remove packages installed with debug

- .circleci/config.yml
- accounts/__init__.py
- accounts/admin.py
- api/permissions.py
- api/urls.py
- exp/admin.py
- exp/views/lab.py
- exp/views/video.py
- project/fields/datetime_aware_jsonfield.py
- project/settings.py
- project/urls.py
- pyproject.toml
- uv.lock
Let's try this again...
Previous PR that was reverted: https://github.com/lookit/lookit-api/pull/1558
> Django 4.0

- project/settings.py
This reverts commit 890455a63890b2930e30c1732043482ecbe499de.
> Revert "remove packages installed with debug (#1578)"

- studies/forms.py
- studies/templates/studies/_image_display.html
- studies/templates/studies/_study_fields.html
- web/templates/web/studies-history.html
- web/templates/web/studies-list.html
- web/templates/web/study-detail.html
For now, we'll skip checking image size on study ads.
> Image name case quick fix

- project/settings.py
Pull images/media from nginx proxy instead of directly from GCP.
> Update media and static url

- project/settings.py
Added settings for our storage options.
> Add storages setting

- project/settings.py
- project/storages.py
- project/urls.py
Staging has debug on, so we'll need to remove media urls for the time being.
> Remove media urls

- project/settings.py
- project/urls.py
- studies/templates/studies/_image_display.html
- studies/templates/studies/_study_fields.html
- web/templates/web/studies-history.html
- web/templates/web/studies-list.html
- web/templates/web/study-detail.html
Now that we're using the static/media proxy, we'll revert the lower case changes and test some more.
> Add storages settings

- project/settings.py
- project/storages.py
- studies/helpers.py
Another iteration in debugging staging.  MEDIA_URL uses the BASE_URL and it must end with a slash.
> BASE_URL must end with a slash

- project/storages.py
Fix the location of where experiments are stored.
> Experiment storage

- project/settings.py
- studies/experiment_builder.py
This is to revert some debugging steps on staging so that we can do the production release.
> clean up debugging

- studies/tasks.py
- studies/templates/studies/study_attachments.html
With the new disk installed, batch downloading of video files has been re-enabled. Additionally, we've added logging to aid in future debugging if needed.
> Batch video download

- studies/tasks.py
This PR builds on the stream zip solution to #1727. I was using some incorrect arguments in the stream zip file iterator. This PR updates the task to include the file mode and correctly specify the compression method.
This also includes some logging for the video file index and count, since the jobs are long-running.
> Video download zip stream: fix incorrect arguments
