lookit/lookit-api

accounts/models.py, api/views.py, studies/serializers.py
- Create Writeable serializer for Response objects
- Use the ids instead of the actual objects so DRF doesn't try to create things.
- Swap in that serializer when creating responses
- Grab the latest demographic data off the specified child's user and use that id
=> Fix Response POST requests

project/settings/defaults.py, project/settings/local-dist.py, project/urls.py, requirements/defaults.txt, web/urls.py, web/views.py
This creates a proxy view that uses `settings.EXPERIMENT_BASE_URL` and proxies  traffic going to /studies/<study_id>/<child_id>/ to `f'{settings.EXPERIMENT_BASE_URL}/studies/{study_id}/{child_id}/'`
Assuming EXPERIMENT_ BASE_URL = 'https://s3.bucket.tld/things/stuff/'
e.g.: https://staging2-lookit.osf.io/studies/uuid1/uuid2/ will proxy to https://s3.bucket.tld/things/stuff/studies/uuid1/uuid2/
It also looks up the child specified in the url by the child id and checks to see if the requesting user has that child associated with them. If the user is anonymous or the child doesn't belong to them they get a 403. If the child doesn't exist they get a 404.
=> Add proxy view, revproxy requirements, and default settings

exp/templates/exp/base.html, project/settings/defaults.py, project/settings/local-dist.py, project/storages.py, project/urls.py, requirements/defaults.txt, studies/templates/studies/study_detail.html, web/migrations/0001_create_initial_flatpages.py, web/static/base.css, web/templates/flatpages/default.html, web/templates/web/base.html
- Add django storage package
- Update static file urls in flatpages
- Update static urls in templates to use static template tag
- Create custom storage engines for media and static files with prefixes
- Update css image path to include prefix
- Update settings to allow for environmental settings for django
storages
- The migration is going to be wrong on prod and local, only correct on staging
- The django-storages should be upgraded on the next release and pinned at 1.6.4, no date set yet
- Local dev will request some static files from staging's GCE storage because flat pages can't use the static template tag without a significant amount of work.
- STATIC_URL should probably pull from an env var.
=> [RFR] Add support for media and static file storage in le cloud

api/views.py, studies/templates/studies/_study_status.html, studies/templates/studies/study_detail.html
Audit API endpoints, making sure that data is properly restricted.  API may be accessed by both participants (who are taking the study) and researchers (who are previewing a study).  This is why a lot of the querysets are either 1) items attached to studies you have permission to view or 2) your own items
=> Feature/API Queryset/Permissions Cleanup

accounts/templates/accounts/researcher_detail.html, accounts/templates/emails/resend_confirmation.html, accounts/templates/emails/resend_confirmation.txt, accounts/templates/emails/reset_password.html, accounts/templates/emails/reset_password.txt, exp/views/user.py, studies/helpers.py
Connect these buttons on the Researcher Detail page.
Enable sending reset password and confirmation emails to researcher through celery.  Really a two-step process.  Sends an email to researcher that gives them the OSF link that will enable them to reset password/resend confirmation email. Not ideal but not sure what else to do.
Test researcher detail page again
Reset password page for participants working ok.
=> Feature/Send Confirmation Emails and Password Reset Emails to Researchers

studies/templates/emails/notify_researchers_of_approval_decision.html, studies/templates/emails/notify_researchers_of_approval_decision.txt
https://openscience.atlassian.net/browse/LEI-462
remove references to comments in approval emails, as the admin has no ability to even leave comments when approving.
also, its currently showing the "rejection" comments in the template for approvals, which is confusing.
=> Feature/Remove comments in approval emails [LEI-462]

accounts/templates/accounts/participant_detail.html, docs/source/django-project-installation.md, docs/source/ember-app-installation.md, docs/source/index.rst, exp/mixins/study_responses_mixin.py, exp/static/exp/css/app.css, studies/templates/studies/study_detail.html, studies/templates/studies/study_participant_email.html
Since researchers may be using the API to get data, the API surfaces only uuid's, not id's, while Experimenter surfaces id's. Show uuid's in places Experimenter-side, to link data.
- Show study uuid on study detail page
- Show participant uuid on participant detail page
- Show participant uuids on study email pages
- Show response/participant/demographic snapshot, and children uuid's on study responses page
- Put ember app/django app installation info in read the docs
=> Feature/Display UUID's Experimenter-Side, more documentation

accounts/signals.py
This makes the signals environmentally aware so that it uses gcloud in staging and prod and `/static/` in development. 
The plus sign on 693 is because python's fstrings don't appreciate javascript inside of them and it was easier than escaping the several billion `{` inside of the rest of the string.
=> Make flatpages use STATIC_URL

docs/source/frames.md, docs/source/index.rst, docs/source/mixins.md, docs/source/random.md, project/settings/defaults.py, studies/templates/emails/custom_email.html, studies/templates/emails/custom_email.txt
Experimenter has changed a lot, but the process for creating frames has not.  Pull over and modify the old frame docs from Experimenter v1 regarding creating frames, mixins in the exp-player and randomization in frames as they are still relevant to the new application.
- Also adds link to custom email where users can change email preferences
=> Feature/Pull in Relevant Docs from Old Experimenter

project/settings/defaults.py, studies/templates/emails/custom_email.html, studies/templates/emails/custom_email.txt
In custom emails to participants, there should be an email link for participants to update their preferences. I had assumed that BASE_URL should have a trailing slash, but it does not on staging, and other emails are built assuming there is no trailing slash
- Remove BASE_URL trailing slash locally to match staging
- Use URL template tag to build email preferences URL instead of manually constructing
=> Feature/Revert Changes to BASE_URL, URL Template Tag to build Email link

api/parsers.py, api/renderers.py, api/tests/test_responses.py, api/utils.py, api/views.py, docs/source/api-documentation.rst, project/settings/defaults.py
https://openscience.atlassian.net/browse/LEI-468
The pref-phys randomizer isn't using information about past sessions from the same child; it's just choosing random conditions each time. The tests here outline what should be happening; the problem is presumably that data from previous sessions isn't being found: https://github.com/CenterForOpenScience/exp-addons/blob/develop/exp-player/tests/unit/randomizers/pref-phys-test.js
Issues was with casing.  Even though the pref-phys randomizer had all the pastSessions, the casing of nested keys were different than what the randomizer expected.  Top level keys should be underscored, but nested keys below top-level should be left as-is.  However the exp-player or the various frames format the nested keys, is how the casing should remain. 
To fix: …
=> [Fix] Parser-Renderer Overrides for Randomization [LEI-468]

docs/source/local-frame-development.md, web/views.py
https://openscience.atlassian.net/browse/LEI-467
From Kim: Video recording isn't working for me or collaborators in Firefox on the staging site (tested on staging-lookit.cos.io), although it does work on lookit.mit.edu and on Chrome. We see a message "Could not load settings" in the Flash player. 
For loading some needed video recording assets, the Chrome referer is this format: `/studies/study_id/child_id/`, but the Firefox referer looks something like `/studies/<study_id>/VideoRecorder.swf` Thanks @icereval for discovering this.
The referrer is split into a list based on the `/` character.  If referer ends in a '/', access study id three spots from end. Otherwise study id is two spots from end.
(While I'm here add Token clarification to docs).
=> Fix/Firefox Video Recording [LEI-467]

studies/templates/emails/custom_email.html
Allow researchers to include \n in participant emails, for readability.
=> allow line breaks in participant emails

.travis.yml, web/templates/web/study-detail.html
* Switch Travis repo owner centerforopenscience -> lookit
* Fix bug in age calculation for study eligibility. Previously a child's age was being calculated by first converting to a moment 'duration', and then converting that back to days. This means that if the child was born, say, February 1st, then on March 1st they would be considered "1 month old" which is 30 days. Actually the child is 28 days old. This was leading to confusion for participants in the Baby Euclid study w/ a narrow age range. It's now fixed & we also display when the child WILL be eligible, so that e.g. someone who's just a few days out of the age range can easily see when they might want to check back.
=> Quick fixes: Update Travis repo and fix age calculation bug

exp/urls.py, exp/views/study.py, studies/templates/studies/_all_json_and_csv_data.html, studies/templates/studies/study_demographics.html, studies/templates/studies/study_responses_all.html
❗️ Do not merge into production yet
Large Downloads are failing with 'Failed - Network error' in Chrome.  This is mostly happening on the All Responses page where you can download all responses to your study in JSON and CSV.  We are currenly showing a preview of all the json or csv responses to your study on the page, and then pushing that code block into a json file or csv file for download.  As the number of study responses grows, this is becoming unwieldy and slow. 
Added four endpoints for downloading data. You must have permission to view study responses to hit these endpoints.
- `/studies/<study_id/responses/all/download_json/`
- `/studies/<study_id/responses/all/download_csv/`
- `/studies/<study_id/responses/demographics/download_json/`
- …
=> [Do not merge into prod] Feature/Download Endpoints for Response Data

project/settings/defaults.py
It looks like moving from the old forked egg to 1.7.1 caused a bit of a regression. I'm going to see if we can get this working with the new, non-forked dependency.
=> Trying to fix a regression with django storages

studies/tasks.py
Context: 
```
"image_build": "b'Sending build context to Docker daemon  10.58MB\\r\\r\\nStep 1/21 : FROM node:8-slim\\n ---> 54f6c4036aa5\\nStep 2/21 : ARG player_addons_concat_sha\\n ---> Running in d72c4a488cfa\\nsymlink XRamp_Global_CA_Root.pem /var/lib/docker/overlay/9cd06d5a622ac05dd858489b2e013e325e4bd2658af81a317ae8206643d827f9/tmproot407205009/etc/ssl/certs/76579174.0: no space left on device\\n'"
```
It looks like the actual problem is state diff between staging and dev. Where I am being sparse with containers and regularly `docker system prune`ing, staging has a bunch of cruft that is probably killing the disk.
I'll have to find a way to deal with this elegantly.
=> Reverting unhelpful commit

ember_build/Dockerfile
Hopefully this fixes our issue with GPG key requests failing, thus allowing docker builds to complete.
=> bypassing gpg nonsense by using debian repo for gosu

studies/tasks.py
Because we don't upload to GCS in the local development environment, in order to test the speed boost in this change, we need to actually test a build in staging.
=> Batch writes to GCS

api/views.py
fixes 500 error on preview view introduced by https://github.com/lookit/lookit-api/pull/271
=> return empty set of responses in API for child TEST_CHILD_DISREGARD

exp/static/exp/css/app.css
This is extremely small but annoying - hopefully we can find another way of dealing with this z-index mess. Too many block formatting contexts for one view! 😒
=> Fixing z-index clobber of summernote options bar with datatables popover

studies/templates/studies/study_participant_contact.html
This fixes a subtle UX bug - default date filter should encapsulate _the past thirty days_, not from the start of the month.
=> more intuitive/reasonable default date filtering behavior

studies/templates/studies/study_responses_consent_ruling.html
Ah, the joys of javascript/jQuery.
Per the API documentation for the .html() method (https://api.jquery.com/html/), an undefined first argument will "dispatch" the getter behavior rather than the setter behavior. We are forcing a value to make sure that the setter is always dispatched.
=> Preclude meaningless getter call by forcing non-null/undefined value

studies/templates/studies/study_participant_analytics.html
ID and ruling are derived straight from the handle instead of the query
parameters. Lesson learned: if you think you've outsmarted the system,
you've lost already.
=> Fixing multiple-series cache issue

studies/templates/studies/study_participant_analytics.html
This is an attempt to fix the improper binned graph rendering that doesn't show nearly the amount of variation that it should
=> properly align date bins on registration graphs

exp/views/study.py, studies/models.py, studies/queries.py, studies/templates/studies/study_responses_consent_ruling.html
The tricky part here was in dealing with the related videos - we still
have to do a bit of testing to see if there's no way to keep the
prefetch as it existed rather than doing the manual join in our app
code.
We've also lost some slight distinction in Consent Ruling comments
between "no previous ruling" and "no comment in previous ruling" due to
the nature of the optimized query.
=> Reduce query load by using .values()

exp/views/study.py
We are using `get_responses_with_current_rulings_and_videos` as the base queryset, effectively - in fact it might make sense to transition this entire view to being based off a ListView at some point and get rid of the study query altogether.
For now, let's just give it a little speed-up.
=> downgrade base queryset in view

project/urls.py
In the old clusters, we had an nginx reverse proxy handling the path for
the favicon. To replicate this old functionality the same way, we'd need
to create an entirely new ingress rule to redirect to the old favicon.ico file.
Considering the fact that we already have the PNG in our staging bucket,
we're just going to let django handle this redirect.
=> Always use PNG favicon with redirect view

cloudbuild.yaml
I believe this will avoid the `fatal: not a git repository (or any parent up to mount point /)` problems we were having before.
=> Bring .git folder into correct location

accounts/models.py, exp/views/study.py, studies/helpers.py, studies/models.py
I skipped the Organization-related ones since we plan to change/remove that model anyway.
Thoughts welcome on how this *should* work. My main motivations are:
- I'd like to be able to manually (via Admin) delete old test studies and responses, especially on staging, to clean things out periodically. Right now that involves manually going through study logs, responses, Videos, consent rulings, etc. and making sure I've gotten everything (in a particular order!), plus going to S3 if I'm feeling ambitious.
- I'd like to make sure we're in a good position to (still manually) delete data if requested by a participant. (We can refine this behavior later in the automated-GDPR-tools ticket.)
=> explicitly choose appropriate on_delete behavior for accounts, studies models

exp/utils.py, exp/views/study.py
Fixes #498 
Previously all elements of the child birthdate list were assumed to be dates, so anything else (specifically None) broke processing into csv/json files. This was likely due to migration of accounts from JamDB system a few years ago (see import_jamdb_participants.py), since format of new data is enforced.
Also upon consideration of the `child_rounded_age` field in the demographic data, make the rounded ages be at the time of the response rather than the time at which the demographic data was saved. (This makes it easier to match to participants and count older/younger siblings, ask if they have an x-year-old sibling, etc.; harder to interpret demographic variables in light of age of children at time of filling out survey - figuring former will be more common.)
=> fix bug about NoneType child birthdates in demographic form

exp/views/contact.py, exp/views/lab.py, exp/views/mixins.py, exp/views/responses.py, exp/views/study.py
This reduce the noise that PyCharm makes when statically analyzing our code, resulting in more meaningful type hints
=> Proposal: use generics to make PyCharm happy

accounts/models.py, accounts/queries.py, accounts/tests.py, studies/templates/emails/study_announcement.html, studies/templates/emails/study_announcement.txt, studies/templates/studies/_study_type.html, studies/tests.py
Sorry for not catching this earlier - we define a year as 365 days throughout, so to avoid people getting notifications when they "age in" but then being told they're not eligible when they get to Lookit (which would be the case for every study for children at least 1 year old), use that definition here too.
=> standardize child age calculation for announcements; update announcement template

accounts/models.py, exp/tests/test_study_forms.py, exp/tests/test_study_views.py, studies/forms.py
* Use ...Lab.object.filter... not user.labs.filter... to choose all labs user has perms for, not just those they're in
* Remove User.labs_user_can_create_study_in which was only used twice in these forms, somewhat circuitously, because it doesn't make sense to import Lab in accounts.models
* Add fairly exhaustive tests
=> fix queryset for labs on study edit/create forms

studies/helpers.py
to avoid error that happens on sendgrid but not local django mail setup
=> decode base64 image string to bytes before turning into mimeimage

cloudbuild.yaml
Sets the Cloud Build timeout to 20 minutes. Builds have been timing out under the default 10-minute time limit.
=> Extend cloudbuild timeout

exp/tests/test_study_views.py, exp/urls.py, exp/views/study.py, studies/templates/studies/study_detail.html
Break up `StudyDetailView` into three views: Managing Researcher Permissions, Changing Study Status, and Cloning Study.
Closes #518 
Tests:
```
poetry run ./manage.py test \
exp.tests.test_study_views.CloneStudyViewTestCase \
exp.tests.test_study_views.ChangeStudyStatusViewTestCase \
exp.tests.test_study_views.ManageResearcherPermissionsViewTestCase
```
=> Clean up StudyDetailView

.travis.yml, exp/tests/test_study_views.py, exp/views/study.py
When a permission was changed and the user was the only admin the view would throw an assertion error.  This error was caught in the post method of the `StudyDetailView`.  I removed the assert in a recent issue, this caused the last admin on a project to have their permission group changed without error.  
To fix this issue, I changed it from a try/catch to a boolean response.  If there's an error on the `manage_researcher_permissions` method then it should return False and then a 403 error will be given.
=> Fix bug when changing permissions ui

studies/forms.py
We found out that there is no warning on running a child more than once on an experiment.  
Additionally, update the location of the help text on the experiment edit form. 
Closes #125
=> Update experiment form help text.

exp/tests/test_analytics_views.py, exp/tests/test_study_views.py, exp/tests/test_user_views.py, exp/views/analytics.py, studies/tests.py, web/templates/web/study-detail.html, web/tests.py, web/views.py
Added tests to verify that specific views aren't showing children that were "deleted".   In one case, There's a test that verifies that even "deleted" children are shown. 
Close #666 
WIP: Still working through list of tasks.  Just wanted to get this off my laptop for the weekend.
=> Ensure soft deleted children aren't shown unnecessarily

accounts/forms.py
Update age range in search filter to cover all ages throughout childhood.  For example, before the age range "1 - 2" and "3 - 4" doesn't include the entire year "2".  This has been fixed by changing age range "1 - 2" to actually cover until age "3".  This has been update will all age ranges.
=> Update age range in search filter

web/tests.py, web/views.py
This PR fixes a bug that was introduced with the recent update to the studies list page filter.  This update should now correctly only display studies that have responses where the field `completed_consent_frame` is False.
=> Update logic for filter "hide studies we've done"

.pre-commit-config.yaml, cloudbuild.yaml
I made some format errors in `cloudbuild.yaml` in a recent PR (#731).  These mistakes could have been caught if pre-commit was linting yaml files.  
This PR adds yaml linting to pre-commit and fixes the found mistakes.
=> Add check-yaml to pre-commit

web/templates/web/studies-list.html
Fixes a bug where the checkbox in the search bar would be selected when the clear button is pressed.  
Note:  This bug shines a light on the fact that we don't have a Splinter/Ghost Inspector/Selenium test suite.
=> Cleared search form will no longer select checkbox

web/static/base.css, web/tests.py, web/views.py
Two issues came out of the recent push to master:
1.  The css looked a bit odd, mainly the border between the left and right sections on the studies list cards.  I removed this border and some unnecessary padding. 
2. The filter was removed when a user changes pages.  This made for an odd experience.  The solution was to no remove the filter values from session and the user will have to press the clear button if they want the for cleared.  The browser's reload button will no longer clear the filter form.
=> No longer remove search form values from session

web/tests.py, web/views.py
Yet another attempt to fix this filter.  The issue this time laid with the confusing documentation around "exclude".  In the end, looking up the studies we want to exclude and then excluding them was a more correct.
=> Fix don't show studies that a child has attempted

web/views.py
Found a small bug in the StudyDetailView that was breaking on error.  Basically, the underscore is overloaded within Django.  It both means a variable that isn't going to be accessed and the function to translate text.
=> Fixed small bug with study detail view

studies/tests.py
This, very simply, adds a check that when a study type is not the study type checked for that it returns a False response.
=> Added check for false study_type

Dockerfile
The previous way of generating translation files (*.mo) wasn't working.  This issue needs to be investigated, but in the mean time, we'll generate the files upon building the docker image.
=> Add compilemessages to dockerfile

web/tests/test_external_views.py, web/views.py
As the subject states, added a test to the history view to verify that only the user that is logged in can view their responses.  There was a small update to the `get_queryset` method, but it doesn't actually change the business logic.
=> history view tests

web/views.py
This PR is to fix the [sentry error](https://sentry.io/organizations/massachusetts-institute-of-technology/issues/2720278140/?environment=production&project=299962&referrer=alert_email).  This fix is included in the rebase from MBAH.
=> Use string formating instead of concatenation

exp/templates/exp/_navigation.html, poetry.lock, pyproject.toml, studies/templates/studies/study_detail.html, studies/templates/studies/study_edit.html, web/templates/flatpages/default.html
This PR resolves an issue found by sonarcloud.io.  It was report a few times, but is the same issue for each instance.  I just added `rel="noopener"` to any `a` tags that had an `href` to an outside link. 
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8kd_losUr7kBuIq65
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8kd9VosUr7kBuIq6e
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8kd8iosUr7kBuIq6D
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8keDposUr7kBuIq8J
- https://sonarcloud.io/project/security_hotspots?id=lookit_lookit-api&hotspots=AXy8keDposUr7kBuIq8L
=> Blank noopener links

exp/tests/test_study_views.py, exp/views/mixins.py, exp/views/study.py, studies/forms.py, studies/templates/studies/_study_fields.html
This PR is to show the "External" and "Scheduled" on the Study Edit Form.  
Closes #861
=> Show external and scheduled in study edit form

poetry.lock, pyproject.toml
Updating the version of boto3 allows the version of urllib3 to increase.  Additionally, the urllib3 package is not directly imported in our project so it is removed from the dependencies list.  Urllib3 needs to be increased above version 1.26 for security reasons.
=> update version of boto3

web/templates/web/participant-signup.html
Researcher registration link was hard to read.  Added class to make link easier to read.  Additionally, updated text to be more clear. 
Closes #703
=> Update researcher registration link text

exp/templates/exp/support.html, web/templates/frontpages/faq.html, web/templates/frontpages/resources.html, web/templates/frontpages/scientists.html
Page titles should be wrapped in h1 tags.  
Closes #719
=> Change h2 to h1 for page titles

web/templates/frontpages/scientists.html
Removed CSS that justified Scientist's Bio info on the scientist page. 
Closes #704
=> Removed css that justify aligned text

studies/templates/studies/_image_display.html, web/templates/web/studies-list.html
Replace existing alt text for study thumbnails.  Instead, use the study name (or title) as the alt text for these thumbnails. 
Closes #716
=> Use study name as alt text for study thumbnail

web/templates/frontpages/faq.html
Remove roles containing "tab" or "tablist".  The FAQ page is the only page I found that has these roles. 
Closes #721
=> Remove roles from faq page

web/templates/web/child-add.html, web/templates/web/children-list.html, web/urls.py, web/views.py
On children list view, moved `add child` button to bottom of list.  Decided that the add child form was odd and overly complex.  Moved the add child form to its own view.
Closes  #951
=> Move add child button

Makefile, docker-compose.yml
This PR covers 4 very small changes:
- Add the RabbitMQ host to the web service within the docker compose script.
- No longer deletes the database on `clean` make target. 
- Removes the docker images on `clean` make target.
- Exposes the database port to host machine so that we can use a database IDE.
=> Add rabbitmq host to web service

Makefile, accounts/tests/test_utils.py, accounts/utils.py, docker-compose.yml, studies/serializers.py
To provide the child hashed id, we needed to first generate it and then inject it into the response API.  To inject the field in the API we're using `SerializerMethodField`.  The function to generate the hashed id, required the Response model object to be in a dictionary form that I was unable to recreate.  To complete this task a bit more quickly, I just wrong a parallel function to the existing one and a unit test to verify that they work the same.  
I am continually working on the docker compose script.  The latest change was to define a temp directory within the container.  This was to remove a warning.
- http://www.tomchristie.com/rest-framework-2-docs/api-guide/fields#serializermethodfield
=> Add child hash id to response

Makefile
A small update to the makefile.  There are now targets for getting access to the psql shell and a target to pipe in SQL file for data import.  These two commands were added to the recent documentation update.
=> Added targets for the database

Dockerfile.web, exp/tests/test_study_forms.py, studies/forms.py, studies/templates/studies/_study_fields.html, web/templates/web/studies-list.html
This PR will allow external studies' `scheduled` checkbox to be changed after save.  
Closes #927
=> Schuduled box editable

studies/templates/studies/study_detail.html
Update the conditional in the template to show the study link when the study type is external.
Closes #970
=> Show study link on external studies

exp/views/study.py, web/views.py
This fixes the MaxRetries error that occurs when running or previewing a study in the local environment. The redirect will switch the request over to the local ember server, so that the developer doesn't have to manually change the port in the browser's address bar. 
https://user-images.githubusercontent.com/9041788/184457166-6d548866-0b16-4393-8daa-6fc84ebbf1c8.mov
Note that the way that the lookit-api and ember tasks interact is still very different on local vs remote environments. This doesn't change that, it just makes local development more convenient by by-passing an error page.
I think we could just check `DEBUG` rather than both `DEBUG` and `ENVIRONMENT` in this line: 
```python
if settings.DEBUG and settings.ENVIRONMENT == "develop":
```
as is currently done here, for example: …
=> redirect to ember server if running in local env

exp/views/study.py, web/views.py
This is to address the issue of broken study links when the user starts the session from the Lookit website that contains a locale code in the path: #973, #1000.
I tried manually removing the locale from the request path for study sessions in this PR: #1008. This does change the request path correclty, but when testing on the staging server, it didn't work: the locale is added back into the path. 
I think the Locale Middleware is altering the request _after_ it's been modified by the ProxyView dispatch methods ([see here](https://docs.djangoproject.com/en/4.1/topics/http/middleware/)). If so then the fix will probably need to involve Django's translation tools and/or the Locale Middleware.
This PR is to see if it's possible to remove the locale from the study session URLs by manually …
=> Remove locale from study links by manually setting language

exp/views/study.py, web/views.py
This is an attempt at #973 and #1000. This is just for testing on staging, since I'm not able to test this locally.
After my last attempt to fix this issue on develop (#1016), I found that, when the URL contains a locale, clicking the study link _does_ load the ember study, but then it produces a 'Page not found' error before making some of the requests that originate from the study JS (specifically the vendor.js file, I think). The requests that aren't made are those starting with `/api/v1/`.
Normal sequence of requests (i.e. no locale in the URL) are shown below. Requests with the red box around them are absent when there's a locale in the Lookit site URL:
Page content and requests with a locale in the Lookit site URL:
So the problem might be with the creation of paths to the study …
=> Fix study links with locale

exp/views/study.py, web/views.py
This is another attempt at fixing #973 and #1000 (but merging should not automatically close those issues).
This PR is to try using `redirect` instead of `super().dispatch` to process the modified URL. This redirect approach is working locally (with and without local, for both preview and real sessions). 
I've also: 
(1) refactored this logic slightly to e.g. remove unnecessary code, such as `else` statements, and improve/clarify variables
(2) removed the manual language activation and setting the request's LANGUAGE_CODE value, since these things were added to test but did not seem to fix the problem.
I have not modified the requests/paths in `ExperimentAssetsProxyView`. It may turn out that the same approach is needed here (i.e. check for locale, remove it, and redirect).
I'll merge this …
=> Fix study links with locale - use redirect

accounts/forms.py
Update to demographics copy.  Specifically, the racial group that's visible when "US" is selected for country.
=> Demophraphics race copy update

ember_build/Dockerfile
The docker file for building experiments is held in this repo.  We needed the version of node increased from 10 to 12 to support AWS SDK.
=> Move node version to 12 for EFP

.travis.yml, Makefile, accounts/tests/test_accounts.py, web/tests/test_views.py
This is another attempt to fix the issue with failing tests in CI.  The previous solution made the CI environment's variables the same as in development.  This solution doesn't fit best practices.  Instead, let's get the development environment to replicate the issues found in CI. 
This PR does a couple of things:
1. The issues in CI were best replicated by unsetting the ENVIRONMENT value.
2. The environment file is no longer copied on travis CI.
=> Another attempt at fixing the failing tests in CI

web/templates/registration/login.html
Per the LMG document, added `autocomplete=off` to the login form element.  
Closes #1085
=> Add autocomplete attribute to form element

studies/models.py
~~This fixes an issue reported in lookit-docs, but that is actually related to the help text shown on the form for creating a new lab~~ (Edit: I transferred the issue from lookit-docs to lookit-api)
Fixes #1094
This change is intended to clarify that the researcher should just enter the slug (URL ending) that they want, not the full URL.
=> Clarify help text for entering lab custom URL slug

studies/forms.py
Fixes #997
This PR changes the placeholder text in the study edit form 'Participant Eligibility Description' to remove the '...who love dinosaurs' part. 
I also added an age range to make it a little clearer to researchers why this field exists (i.e. to translate the actual study criteria that might be in a non-intuitive form, such as an age range in days, into a more human readable version).
=> edit criteria placeholder text in study create/edit form - #997

web/templates/web/studies-history.html, web/templatetags/web_extras.py
This fixes a bug on `bootstrap-5` in the `studies/history` view where the message "You have not yet participated in any external studies." message is shown when the user views their history of _internal_ studies and the list is empty. 
Old:
I think this was happening because, when the study list is empty, this line in the template file always returns false (presumably because `study` or `study_type` doesn't exist?).
```
{% if study.study_type.is_ember_frame_player %}
```
This PR fixes the problem by replacing the conditional for study type with a filter method for the determining the selected tab (currently just Lookit vs external, though it will continue to work if we add more tabs), so that the form can use the tab selection to set the appropriate message text.
Fix:
=> Bootstrap 5 studies history bug fix

web/templates/web/contact.html, web/templates/web/faq.html, web/templates/web/privacy.html, web/templates/web/termsofuse.html
These are the Bootstrap 5 changes to the privacy, contact and terms of use pages. Also some minor changes to the FAQ page for consistency.
Sorry that the file diffs aren't particularly helpful. I followed CJ's lead and tried to remove unnecessary markup. The headers and margins should be consistent across these pages now. I did use some container divs around the content to help with formatting, but can change/remove this. Just let me know.
=> Bootstrap 5 privacy, contact, terms of use

accounts/templates/accounts/participant_detail.html
This is a fix for the participant detail view.  The other version of this view was missing the "gestational age" and "additional info" for each child.
=> Bootstrap 5 exp participant detail fix

exp/templates/exp/_navigation.html, web/templates/web/_navigation.html, web/templatetags/web_extras.py
Bootstrap 5 changes to the experimenter app navigation bar. 
This is styled to match the web app nav bar, with some minor spacing differences to make the nav items fit nicely.
I also removed the "Recruitment Stats" (analytics page) navigation item from the experimenter nav bar because we have not updated that page for bootstrap 5.
Wide window
Narrow window
Help dropdown
Account dropdown
=> Bootstrap 5 experimenter nav bar

Makefile, accounts/templates/accounts/participant_detail.html, studies/templates/studies/_all_json_and_csv_data.html, studies/templates/studies/lab_create.html, studies/templates/studies/lab_detail.html, studies/templates/studies/lab_member_list.html, studies/templates/studies/lab_update.html, studies/templates/studies/study_attachments.html, studies/templates/studies/study_detail.html, studies/templates/studies/study_edit.html, studies/templates/studies/study_form.html, studies/templates/studies/study_participant_contact.html, studies/templates/studies/study_responses.html, studies/templates/studies/study_responses_consent_ruling.html, web/templates/web/base.html, web/templatetags/web_extras.py
Adds template tag for breadcrumb navigation bar.  This should normalize the breadcrumb style across all views.
=> Breadcrumb

accounts/templates/accounts/2fa-setup.html, accounts/templates/accounts/participant_list.html, studies/templates/studies/_all_json_and_csv_data.html, studies/templates/studies/_study_type.html, studies/templates/studies/lab_list.html, studies/templates/studies/lab_update.html, studies/templates/studies/study_attachments.html, studies/templates/studies/study_detail.html, studies/templates/studies/study_detail/_manage_researchers.html, studies/templates/studies/study_detail/_modal.html, studies/templates/studies/study_detail/_study_status.html, studies/templates/studies/study_edit.html, studies/templates/studies/study_form.html, studies/templates/studies/study_list.html, studies/templates/studies/study_responses.html, studies/templates/studies/study_responses_consent_ruling.html, web/static/js/study-detail.js, web/templates/registration/password_reset_complete.html, web/templates/registration/password_reset_confirm.html, web/templates/registration/password_reset_form.html, web/templates/web/child-add.html, web/templates/web/child-update.html, web/templates/web/children-list.html, web/templates/web/home.html, web/templates/web/participant-email-preferences.html, web/templates/web/studies-history.html, web/templates/web/study-detail.html, web/templatetags/web_extras.py
This PR makes the button classes/styling consistent across views. It moves the primary and secondary button classes into template tags in `web_extras` and replaces all primary/secondary button classes with values from these template tags. We can easily change the specific styling for the primary/secondary buttons. The point of this PR is to make them all consistent.
- Primary (positive action) buttons: **CHS blue background and black text**
- Secondary (cancel and 'less important') buttons: **light gray background and dark gray text/border**
- **There are no more green buttons**.
- Navigation bar on the experimenter manage studies page now matches the main navigation bar (i.e. gray with a filled button for the active nav item, rather than link styling).
**Green/Success**
Please let me …
=> BS5 button classes

accounts/templates/accounts/participant_detail.html, accounts/templates/accounts/participant_list.html, exp/templates/exp/support.html, studies/templates/studies/_all_json_and_csv_data.html, studies/templates/studies/lab_create.html, studies/templates/studies/lab_detail.html, studies/templates/studies/lab_list.html, studies/templates/studies/lab_update.html, studies/templates/studies/study_attachments.html, studies/templates/studies/study_detail.html, studies/templates/studies/study_edit.html, studies/templates/studies/study_form.html, studies/templates/studies/study_list.html, studies/templates/studies/study_responses.html, studies/templates/studies/study_responses_consent_ruling.html, web/static/js/resources.js, web/templates/web/base.html, web/templates/web/contact.html, web/templates/web/faq.html, web/templates/web/lab-studies-list.html, web/templates/web/privacy.html, web/templates/web/resources.html, web/templates/web/scientists.html, web/templates/web/termsofuse.html, web/templatetags/web_extras.py
This PR is to standardize (1) the spacing between the navigation bar, page heading(s) and/or the rest of the page content, and (2) the indentation of content relative to the navigation bar. Example screenshots below.
I've created template tags for BS5 classes for the page's container div, main title/heading (h1) and subheadings. However so far I've only implemented these in a small subset of pages in the web app. I will add more pages to this PR ASAP as I get them done.
I also made a small change to the state drop-down selection on the Resources page: I added "Select a state" to the default/blank option.
=> BS5 content and navbar spacing

scss/custom.scss, web/static/custom_bootstrap5.css
In the recent BS5 update, we change the a tag color specifically.  This left an uneven color change throughout the site.  A reasonable fix at this moment is to simply adjust the Blue color to be the darker blue color.
=> Remove custom a tag color and update general blue

accounts/templates/accounts/2fa-setup.html, accounts/templates/accounts/account-update.html, accounts/templates/accounts/researcher-registration.html, studies/templates/studies/lab_create.html, studies/templates/studies/lab_member_list.html, studies/templates/studies/lab_update.html, studies/templates/studies/study_edit.html, studies/templates/studies/study_form.html, studies/templates/studies/study_participant_contact.html, web/templates/registration/login.html, web/templates/registration/password_reset_confirm.html, web/templates/registration/password_reset_form.html, web/templates/web/child-add.html, web/templates/web/child-update.html, web/templates/web/demographic-data-update.html, web/templates/web/participant-email-preferences.html, web/templates/web/participant-signup.html, web/templatetags/web_extras.py
This PR adds a template tag to assist with styling form buttons.  Currently, all form buttons are aligned right.
=> Form buttons right

accounts/templates/accounts/participant_list.html, scss/base.scss, studies/templates/studies/lab_list.html, studies/templates/studies/lab_member_list.html, studies/templates/studies/study_attachments.html, studies/templates/studies/study_list.html, web/static/custom_bootstrap5.css, web/templates/web/studies-list.html
Add a CSS class to center search bars.  For studies list, added appropriate BS5 classes to style filter/search bar.
=> Add class to center search bars

studies/experiment_builder.py
This adds the S3 environment variables to the `run_docker_container` method in the `EmberFrameplayerBuilder` class. This is a test to see if these variables will be successfully passed into the EFP study.
This is just intended for testing on staging, and changes will be reverted after testing.
=> pass S3 environment variables into run_docker_container in EFP builder class

web/templates/web/studies-history.html
This PR contains updates to the explainer text that appears below the "Lookit studies" and "External studies" tabs on the "My Past Studies" (studies history) page.
**One or more study**
> "Lookit studies run here on our platform, and usually include a video of your session! You can find information about your previous study sessions, watch these videos, and see comments left by researchers below."
**No studies**
> "Lookit studies run here on our platform, and usually include a video of your session! You have not participated in any Lookit studies."
**One or more study**
> "External studies happen at other websites, and are listed below after you click the "Participate Now" button to follow a link. You can find information on the studies you have accessed and contact information for the …
=> Edit explainer text on Studies History for CHS merger

web/templates/web/base.html
This PR changes the ending of all page titles from ' - Lookit' to ' - Children Helping Science'.
=> Change page title ending to Children Helping Science for merger

web/templates/web/resources.html
As part of our upcoming merger with CHS, this PR removes the reference to the separate CHS site in the "Other ways to participate from home" section on the Resources page. This just leaves SciStarter as the only link in that section.
=> Remove reference to CHS on Resources for merger

accounts/forms.py
Fixes #1193 
Researchers might come back to the CHS site after not logging in for a long time. This change to the 2FA prompt is to remind researchers that they can find their one-time password in the Google Authenticator app on their mobile device.
=> Edit help text/prompt for entering OTP

api/views.py, exp/tests/test_video_views.py, exp/views/analytics.py, exp/views/responses.py, studies/tests.py
This PR fixes the `test_correct_message_structure` test in `studies/tests.py` that can fail due to a mismatch in the order of elements between two lists. The order mismatch occurs because the `all` method on querysets does not necessarily return objects in the same order. This PR fixes the problem by comparing sets of objects rather than lists.
Also, the test result output contains logs and warnings that make it difficult to see clearly whether the tests are running as expected, or if there's anything that needs to be fixed. This PR does two other things to clean up the test result output. 
1. Disables logging for non-critical issues during the `CheckPipeProcessingTestCase` tests, since these tests always produce error logs (due to `Video` model …
=> fix test: sometimes fails due to list order mismatch

accounts/templates/accounts/participant_list.html, exp/views/user.py
Closes #1037
Fix sorting on view participants page.
=> Sorting not working in view participants

project/settings.py
Add value to Django settings to have "HttpOnly" flag set on cookies.  This all cookies (There's only two right now) except the CSRF cookie.  This value is readily available in the html and there's little reason to set it.  See [this post](https://security.stackexchange.com/questions/175536/does-a-csrf-cookie-need-to-be-httponly) for more information on the security theater that is the "HttpOnly" flag.  
Closes #1080
=> Set cookies to have HttpOnly set

exp/views/study.py, studies/templates/studies/experiment_runner/efp_edit.html, web/static/js/efp-runner.js
Closes #1275
Github's API uses by default the default branch of a repo.  For EFP this was develop.  Updated API calls to specifically use the master branch.
=> Update github api to pull from EFP's master branch

exp/tests/test_runner_forms.py, studies/forms.py, web/static/js/efp-runner.js
Closes #1043 
In the EFP config, it was confusing to have to validate JSON when the generator is used.  
To resolve this, we moved the "use_generator" checkbox to the top of the form.  When it's not checked, the JSON protocol field is visible and the generator field will NOT be validated.  The reverse is true when the "use_generator" checkbox is checked.
=> Diable json validation when using generator

accounts/forms.py, accounts/templates/widgets/birthday.html, accounts/widgets.py, web/static/js/child-add.js
Closes  #1096
For a child's birthday, it was encoded as `month/day/year`.  This can be confusing to those who don't order their dates this way.  To resolve this issue we changed the widget on the child's form for the birthday field to the [SelectDateWidget](https://docs.djangoproject.com/en/4.2/ref/forms/widgets/#django.forms.SelectDateWidget).  This provided to the localization needed for date fields.  
Additionally, some code clean up and an update to the age display JavaScript. 
Add Child English:
Add Child French:
Update Child English:
Update Child French:
=> Changing birth year format

web/static/js/study-detail-web.js, web/templates/web/study-detail.html, web/templatetags/web_extras.py
Fixes #1288
On the study detail page, this PR adds in a check for the child's prior study participation criteria (in addition to the existing checks against age range and criteria expression). Therefore a warning is shown when the child is ineligible due to prior study participation.
See example screenshots from #1288. 
In the screenshot below, the selected child is not eligible for the study only due to not having participated in another study. The change in this PR produces in a warning message for this case.
=> Add warning when ineligible due to study participation criteria

exp/views/responses.py, project/settings.py, studies/queries.py, studies/templates/studies/study_responses_consent_ruling.html
This PR is in response to issue #1291 
Now, on the consent ruling page for a study, when a user clicks on a given consent to rule on, the user's location will be collated with the rest of the info under "Session Data"
The changes required for this were fairly minimal. The consent_ruling data query already grabs "demographic_snapshot_id" from the response row, so I just had to add "demographic_snapshot" when calling "select_related" for "child" and "child__user".
=> Add country + state from demographic data to session data on consent ruling page (Closes #1291)

accounts/queries.py, accounts/tests/test_accounts.py
This PR makes a few changes to the 'must have/not have participated' Study eligibility criteria:
- When the study has more than one required (must have participated) study, the child must have participated in ALL of these in order to be eligible (#1306)
- When checking the child's eligibility, we now ignore empty (sequence=[]) responses to internal studies (#1302)
- Adds tests for more complex eligibility cases (e.g. study has multiple required or disallowed prior participation criteria, study has both required and disallowed participation criteria, required/disallowed studies are external/internal and responses are empty/non-empty)
=> Prior participation eligibility logic (#1302, #1306)

studies/templates/studies/experiment_runner/base.html, studies/templates/studies/experiment_runner/efp_edit.html, web/static/js/efp-runner.js, web/templatetags/web_extras.py
There's a bug in production where the breadcrumbs aren't being displayed.  This validation was using the breadcrumbs element as a reference to place the JS errors on the EFP runner edit form. This removes the need for the breadcrumbs reference.
=> Fixed issue with js errors not showing in ui.

web/static/js/js-validation.js
JSHint's warning for using [dot notation over bracket notation is deprecated](https://jshint.com/docs/options/#sub).  They provide an option to remove this warning.  
This PR adds that option to remove the warning to the jshint config.
=> Remove JSHint warning

web/static/js/js-validation.js
For the study cloned [here](https://childrenhelpingscience.com/exp/studies/3294/), JSHint wasn't returning two errors.  We can find these errors by putting the JS code into JSHint's [sandbox](https://jshint.com/).  I added an [option](https://jshint.com/docs/options/) that will report errors for undefined variables.  The other semi-obvious error we could add would be "unused", but this gives us error for the function that wraps the user's code.  
The warning message "Too many errors" comes from the ace editor.  This doesn't prevent the user from saving their code, but it's not great.  The bug is reported in many different places, still searching for a solution.
=> Add error "undef" to jshint

api/urls.py, api/views.py, studies/templates/studies/experiment_runner/efp_edit.html, studies/templates/studies/experiment_runner/jspsych_edit.html, web/static/js/js-validation.js, web/templates/web/base.html, web/templates/web/jspsych-study-detail.html
Closes #1294
Now that the lookit-helpers package is fairly close to being released to NPM, we can implement it in the JSPsych template.  
1. The existing linter for researcher code was proving to be difficult as we moved away from ES6.  A modular version of Babel is used instead.  
2. Added endpoint "past-sessions" to fulfill the need for researchers to know the past sessions (or responses) a user has done on their experiment.
=> Jspsych helpers

accounts/models.py, exp/tests/test_contact_views.py, exp/tests/test_study_views.py, exp/views/lab.py, exp/views/study.py, studies/helpers.py, studies/tasks.py, studies/tests.py
Fixes #1356
This PR does two key things:
1. Removes the optional 'from_email' argument from the `send_email` helper function, because we are now always sending email from the default MIT email address (specifically the `EMAIL_FROM_ADDRESS` in project settings).
2. In cases where we were sending email "from" a lab email address, this PR adds the lab email to the "reply-to" email header.
A few implementation notes:
- The reply-to must be a list or tuple, hence the square brackets around the lab email address in the reply-to argument.
- I didn't need to modify every `send_mail` call in the codebase because the 'from_email' argument was optional, and when omitted, it defaulted to sending from the project's default 'from' address. 
- The `send_mail` function is mocked in …
=> Send all emails from same MIT domain and move lab email to reply-to

exp/urls.py, web/urls.py
Closes  #1325
This issue was hoping to have the same URL for all experiment runners.  After some research, redirecting to the reverse proxy prevents us from having a single URL for all runners.  The solution we leaned into was to provide a unique URL for each experiment runner.
Here are the URLs for the two experiment runners we currently support. 
- EFP: studies/`study_uuid`/`child_uuid`/
- jsPsych: studies/j/`study_uuid`/`child_uuid`/
The single "j" in the URL provides us with the uniqueness to tell them apart without necessarily exposing additional data to the experiment participant. Additionally, this leaves the EFP URL as it was, so no legacy URLs need to be updated.
=> Updated jspsych urls

studies/templates/emails/base.html, studies/templates/emails/base.txt, studies/tests.py
Closes #1364
This PR simply adds an email to link to the bottom of the footer for participant emails.
=> Add questions/feedback link to participant emails

web/templates/web/jspsych-study-detail.html
In a [recent PR](https://github.com/lookit/lookit-jspsych/pull/21) on the lookit-jspysch repo, we reset the version of our packages to `0.0.1`. This PR updates the lookit-jspysch packages in use in this repo.
=> Update links to lookit's unpkg packages

studies/templates/emails/base.html, studies/tests.py
This PR puts line breaks between the three links at the bottom of participant emails, so they don't appear all on the same line (see screenshot). This issue only affects the HTML version of the base template.
=> move email footer links to new lines

Makefile, locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/es_AR/LC_MESSAGES/django.po, locale/eu/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/fr_CA/LC_MESSAGES/django.po, locale/he/LC_MESSAGES/django.po, locale/hu/LC_MESSAGES/django.po, locale/it/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/ko/LC_MESSAGES/django.po, locale/nb/LC_MESSAGES/django.po, locale/nl/LC_MESSAGES/django.po, locale/no/LC_MESSAGES/django.po, locale/pl/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/pt_PT/LC_MESSAGES/django.po, locale/ro/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, locale/tr/LC_MESSAGES/django.po, locale/zh_HANS/LC_MESSAGES/django.po, web/templates/web/study-detail.html
Fixes #1373
This PR does the following:
- Updates all translation .po files. These are out-of-date (all last updated in 2021?) and therefore are missing some text translations and include some translations that are no longer used. 
- Parameterizes the contact information in this case: 
> trans "This study is conducted by " + contact
so that the `contact` text is passed into the translation string as an argument. Now the translation is written as:
> "This study is conducted by %(contact)s."
This allows the translator to move the 'contact' text to a different part of the sentence, which is a requirement for the Hungarian translation.
- Updates all translation text for the "This study is conducted by" string to include the new 'contact' argument in the translation. In all cases, the …
=> Parameterize and update translations

exp/tests/test_runner_views.py, exp/urls.py, exp/views/study.py, studies/templates/studies/experiment_runner/base.html, studies/templates/studies/study_detail.html, studies/templates/studies/study_edit.html, web/templates/web/faq.html, web/urls.py, web/views.py
The copy on a few study edit buttons was confusing.  This PR changes that copy. 
Closes #1378 
The card titles and buttons were updated as requested.  The URL `name` attribute was also updated to reflect the copy. 
jsPsych study type:
Internal study type:
External study type:
=> Update study edit UI

locale/de/LC_MESSAGES/django.po, locale/es/LC_MESSAGES/django.po, locale/es_AR/LC_MESSAGES/django.po, locale/eu/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, locale/fr_CA/LC_MESSAGES/django.po, locale/he/LC_MESSAGES/django.po, locale/hu/LC_MESSAGES/django.po, locale/it/LC_MESSAGES/django.po, locale/ja/LC_MESSAGES/django.po, locale/ko/LC_MESSAGES/django.po, locale/nb/LC_MESSAGES/django.po, locale/nl/LC_MESSAGES/django.po, locale/no/LC_MESSAGES/django.po, locale/pl/LC_MESSAGES/django.po, locale/pt_BR/LC_MESSAGES/django.po, locale/pt_PT/LC_MESSAGES/django.po, locale/ro/LC_MESSAGES/django.po, locale/ru/LC_MESSAGES/django.po, locale/tr/LC_MESSAGES/django.po, locale/zh_HANS/LC_MESSAGES/django.po, web/templates/web/_navigation.html, web/templatetags/web_extras.py
This PR fixes a problem with the navigation bar button labels not being translated. The problem was related to how we were generating the navigation bar buttons, which was causing Django to not pick up the button text as needing translation.
While testing the translation updates, I noticed that some of the navigation bar button labels weren't being added to the translation (.po) files. A while ago we changed the way that we create the nav buttons in the templates (with a custom `nav_link` template tag) but it turns out that translating the text within that template tag meant that the text wasn't being picked up by Django and added to the .po file. This fixes the problem by translating the text in the template first, before passing the translation as an argument into the `nav_link` tag. I …
=> Fix nav button translations

accounts/forms.py
[Sentry Issue](https://massachusetts-institute-of-technology.sentry.io/issues/5080130387/events/e7fdbc7ab1a94a69acfe53220c32b894/)
This PR adds a check before verifying OTP.  I am not entirely sure why this is happening, but it's simple enough to check if the OTP object not None before the verify.
=> Sentry: AttributeError  /2fa-login/

accounts/forms.py, accounts/tests/test_forms.py
[Sentry Issue](https://massachusetts-institute-of-technology.sentry.io/issues/3005539080/events/d27ab00de892428ab5edd21f65563da0/)
If there's no key value "Child" on data, then it'll throw a `KeyError`.  Using dictionary's get method should solve this problem.
=> Sentry: KeyError  /studies/

project/settings.py, studies/tests.py, web/urls.py
Upon adding a "unsubscribe email" link to the end of our user's emails, showed us that there are some unfortunately messy usernames in our database.  It seems that this bug has been fixed, but the data wasn't cleaned up.  This PR loosens the restrictions on the unsubscribe email link and we'll have to run some SQL scripts to clean up usernames.
Additionally, there is a "fix" for an error (see below) that celery is generating.  
```
lookit-api-broker  | 2024-07-02 16:03:51.534 [info] <0.779.0> accepting AMQP connection <0.779.0> (172.18.0.5:36826 -> 172.18.0.3:5672)
lookit-api-broker  | 2024-07-02 16:03:51.536 [info] <0.779.0> connection <0.779.0> (172.18.0.5:36826 -> 172.18.0.3:5672): user 'lookit-admin' authenticated and granted access to vhost '/'
lookit-api-broker  | 2024-07-02 …
```
=> Handle Malformed Usernames

studies/models.py, studies/tasks.py
Fixes #1430
This PR fixes the Video.DoesNotExist error that we're getting in the celery `delete_video_from_cloud` task. The error is happening because the delete video task is running after the video object has been deleted, but then the code inside the task is trying to reference the deleted video object. The video object is being referenced in order to figure out which AWS bucket to delete the video from. So instead of looking for that information inside the task code, we can pass it in as an argument when the task is first set up.
**Implementation notes:**
- When jsPsych studies are added, we will have 3 possibilities for video storage buckets. Thus the current "pipe or not pipe" logic for the `delete_video_from_cloud` task will need to change. We could either change the …
=> Fix Video.DoesNotExist error when deleting videos from cloud

Makefile, exp/views/study.py, studies/helpers.py, web/views.py
A quick PR to fix an issue found with reviewing JsPsych studies.  
When we start any experiment, we also create a response.  If you make a response and don't set the study type, it will default to E.F.P. even though you have provided a study.  When creating JsPsych studies, I created the response and stated the study type but forgot to update when a researcher would review a study.  These are two different views.  This PR places the creation of a response for a JsPsych study into a single function.
=> Fix issue when attempting to review jspsych study

studies/models.py
This is a small addition of conditionals to two lines in the most_recent_ruling_comment and most_recent_ruling_arbiter functions of the Response data model. The model specifies that both fields are allowable as null, so the conditionals account for this by checking that they are not none before trying to access their properties.
=> Bug fix for null values of ConsentRuling model

Makefile, exp/views/responses.py, studies/models.py
Closes #1467
When attempting to download PsychDS formatted data for a jsPsych experiment, the site would throw 500.  The issue is how the jsPsych experiment data is formatted.  This was easily solved by converting the sequence and experiment data into a dictionary and providing it to PsychDS.
=> Jspsych framedata psychds

exp/views/responses.py
Closes #1468
The file download by clicking the "CSV" button in the "Child Data" section of the "All Responses" view would have a double extension.  This PR changes ".csv.csv" to ".csv".
=> Remove unnecessary ".csv" in filename

exp/views/study.py, web/templates/web/jspsych-study-detail.html, web/views.py
This PR generates temporary AWS credentials and passes them into the jsPsych study template, where they can be retrieved and used by the lookit-jspsych `data` package. We're using the maximum duration for these credentials, which is 36 hours.
**Screenshots**
The temporary AWS credentials have to be requested each time a user tries to start a jsPsych study. If for some reason there's an error obtaining those credentials, the user is redirected back to the study/preview details page, and they'll see an error message.
=> AWS video upload credentials for jsPsych studies

web/templates/web/jspsych-study-detail.html
This PR adds the jsPsych `video-button-response` plugin to the set of automatically loaded plugins for jsPsych studies.
=> Add jsPsych `video-button-response` plugin

studies/test_recording_method.py, web/templates/web/jspsych-study-detail.html
This PR moves the following to production:
- Add video-button-response to jsPsych studies: https://github.com/lookit/lookit-api/pull/1488
- Add tests for recording method types: https://github.com/lookit/lookit-api/pull/1485
=> Add jsPsych plugin and recording method tests to production

studies/tasks.py, studies/tests.py
Fixes #1495
This PR fixes a key error in the "cleanup incomplete videos" task, which was caused by the "Uploads" key not existing in the AWS API response. 
First, this changes the conditional statement to prevent the error from being thrown when "Uploads" does not exist in the response. 
Second, this adds a log statement with the response when it doesn't contain the "Uploads" key, so that I can figure out when/why this happens. Once I have that information, I should be able to remove the log message and handle this case another way.
=> Key error in incomplete videos task

exp/views/responses.py
This is a one-line change to the psych-DS response download function, with the name of the generated ignore file being changed from .psychdsignore to .psychds-ignore
=> change filename of psychdsignore in response download

exp/tests/test_contact_views.py, exp/views/contact.py, scss/study-responses.scss, studies/templates/studies/study_participant_contact.html, studies/templates/studies/study_responses.html, web/static/custom_bootstrap5.css, web/static/js/study-participant-contact.js, web/static/js/study-responses.js
The grey info box at the top right side of the individual response view is now updated with selections from the table.  Additionally, the link to contact participants' view will auto-populate the recipients field if their filter allows. 
https://github.com/user-attachments/assets/43ee6a73-7abe-40dc-a92b-385f58de138a
https://github.com/user-attachments/assets/fed09f4c-a207-4804-a879-49995196a8a7
=> Individual response info box

studies/templates/studies/study_responses.html, web/static/js/study-responses.js
Add column "Time Elapsed" to Individual Response table.  This column is a differently formatted version of the Date column and uses the data from the Date column to sort itself.  It's possible that these two columns could be the same column.
=> Add "Time Elapsed" column

exp/urls.py, exp/views/responses.py, scss/study-responses.scss, studies/templates/studies/study_responses.html, web/static/custom_bootstrap5.css, web/static/js/study-responses.js
This PR adds data saving to the researcher-editable fields in the Individual Responses table.
- Adds JavaScript to update the Response object in the database when the researcher-editable column values changes.
- Adds an endpoint that processes the POST request sent from the IR page. The `StudyResponseSetResearcherFields` view checks the following:
- User is a researcher with `EDIT_STUDY_FEEDBACK` permissions for this study
- Response object exists and is a response to this study
- The field that was changed is one of the researcher-editable Response fields (session_status, payment_status, star)
- The value is valid for that field - one of the allowed status options (for payment/session status) or a boolean (star).
- Adds a CSRF token and the endpoint URL to the IR page template.
- Adds …
=> IR Table: Update database when values change

studies/templates/studies/study_responses.html
If user doesn't have edit feedback permissions on this study, disable "payment status", "session status", and "star" columns.
=> Conditionally disable field based on user permission

studies/templates/studies/study_responses.html
This PR fixes a bug with the data updating for Star values. 
The input element was always in an 'unchecked' state when the page loaded (regardless of the Star value in the database and the filled/unfilled star that was shown). When we send the data back to the server, we check the 'checked' state of the input element and use that as the new value. This meant that, upon changing a Star value, it was always changed from False to True. 
This PR fixes the problem by setting the input element's "checked" state according to the response's Star value when the page loads, so that when the Star value is changed, the value is updated correctly.
https://github.com/user-attachments/assets/03da778c-8e99-4da2-9929-e33442990535
=> IR table: fix bug with Star values

studies/templates/studies/study_responses.html, web/static/js/study-responses.js
The information displayed at the IR view's top looks odd when there's no response data.  
Don't show that row when there's no response data.
=> Handle IR table when there's no resp data

studies/queries.py
In the info row on the IR view, the statistics data displayed an empty string when there was no data for a category.  We'll instead have a 0 when there's no data.
=> Display a 0 instead of empty string

web/static/js/study-responses.js
This PR fixes a bug in the Individual Responses table, where the Date column was being sorted as a string rather than date.
=> IR table: fix bug in date column sorting

.sonarcloud.properties, exp/tests/test_response_views.py
This PR adds tests for the new exp `StudyResponseSetResearcherFields` view that is used to update the researcher-editable fields for responses. This view accepts a POST request sent from the IR page when a researcher changes the value of one of the editable fields in the table.
- Researchers without 'edit study feedback' permissions for the study cannot change any of the researcher-editable response values (POST request fails with 403 Forbidden).
- Researchers with 'edit study feedback' permissions for the study can change any of the researcher-editable response values (POST request succeeds with 200 ok and response field/value is changed in database).
- The new researcher-editable fields are included in the CSV and JSON response data downloads.
- The POST request fails for the following …
=> Add tests for new researcher-editable response fields

project/storages.py
After releases there are some who find the site broken.  This is due to their browser having cached files that need to be updated.  
Add a short md5 hash to the the end of static files.  
This _should_ work, but testing on staging will be needed.
=> Add short hash to the end of static file names

project/storages.py
This reverts commit db645cd678987afa1383954ee6329fef377e5f2c.
We don't know what happened with this release.  The filenames were changed as expected, but the deployment failed.  This PR reverts the last commit.
=> Revert "Add short hash to the end of static file names (#1538)"

web/templates/web/jspsych-study-detail.html
This PR modifies the jsPsych study template to update two CHS jsPsych packages to their latest versions:
- lookit-initjspsych v2.0.1
- record v3.0.1
The details of package updates are here: https://github.com/lookit/lookit-jspsych/pull/125
I tested these unpkg links locally with the following tests:
- Recording in Chrome and playing back the recording in both FF and Chrome: https://github.com/lookit/lookit-jspsych/pull/127
- Running a jsPsych study that contains a [nested timeline](https://www.jspsych.org/latest/overview/timeline/#nested-timelines), timeline node, [timeline variables](https://www.jspsych.org/latest/overview/timeline/#timeline-variables), [looping timeline](https://www.jspsych.org/latest/overview/timeline/#looping-timelines), and [conditional …
=> Update CHS-jsPsych packages lookit-initjspsych (v2.0.1) and record (v3.0.1)

exp/views/responses.py
This PR updates the queryset for the Individual Responses page view to reduce the number of hits to the database. A number of other object lookups related to the study and response are required for this view: study type, child, participant/user, demographic snapshot, videos. These relationships were causing the [N+1 query problem](https://dev.to/herchila/how-to-avoid-n1-queries-in-django-tips-and-solutions-2ajo) because they were being retrieved separately for each response in a loop.
I used `select_related` to get the related objects that we need for the relevant set of Response objects, but this could probably still be improved.
For instance, we could try just grabbing the specific columns/values we need from each of these foreign key objects. But this is tricky because the info we need …
=> IR page: improve queryset

web/static/js/study-responses.js
This PR fixes a bug that was causing the date column not to sort properly. I believe the problem was caused by the date column losing access to the full timestamp. After multiple failed attempts at fixing this through datatables datetime formatting, I decided to sort the Date column on the Response ID value (which increases incrementally with the creation of each new response object).
@okaycj I'm not entirely sure why, but this change seems to fix the row re-sorting bug that was triggered by `updateAJAXCellData`, but please feel free to check too. I can also test again tomorrow and on staging.
=> IR table: sort date using Response ID

exp/views/responses.py, scss/study-responses.scss, studies/templates/studies/study_responses.html, web/static/custom_bootstrap5.css, web/static/js/study-responses.js
This PR replaces the bootstrap icon template tags with fontawesome icons as the stars in the "Star" column.
For some reason, the `bs_icon` template tags we were using to generate the filled/unfilled stars for the "Star" column were causing significant page load delays. I looked into options for replacing them, and found that loading fontawesome icons from a kit link is faster. 
I tested the loading times by finding a study in my local DB that has a large number of responses (997). I loaded the Individual Response page for this study on two different branches: develop and this one (ir-page-timeout-icons). Here are the loading times on the two branches, with browser caching disabled:
| branch  | load time (min) | load time (sec) |
| ------------- | ------------- | ------------- |
| develop …
=> IR page: replace bootstrap star icons with fontawesome

web/templates/web/jspsych-study-detail.html
This PR adds the following jsPsych plugins to the study template:
- survey-text v2.1.0
- survey-multi-choice v2.1.0
This gives researchers the option to use these plugins in their experiments, and doesn't change anything else about CHS jsPsych studies/code.
These are the latest versions of these plugins and compatible with the jsPsych core version that we're using (v8.0.3, and these both require jspsych >=7.1.0).
Fixes #1544
=> Add jsPsych survey-text and survey-multi-choice

.sonarcloud.properties, exp/tests/test_response_views.py, exp/views/responses.py, project/storages.py, scss/study-responses.scss, studies/templates/studies/study_responses.html, web/static/custom_bootstrap5.css, web/static/js/study-responses.js, web/templates/web/jspsych-study-detail.html
This PR moves the following changes into production:
**Individual Responses page**
- Attempt to fix, or at least improve, the loading duration/timeout problems
**jsPsych studies**
- Update the CHS lookit-initjspsych package version to fix a problem with nested timelines and timeline nodes (https://github.com/lookit/lookit-jspsych/issues/130).
- Update the CHS record package version to fix a problem with video recording playback (https://github.com/lookit/lookit-jspsych/issues/126)
- Load the jsPsych survey-text and survey-multi-choice plugins (short-term solution for researchers who are having problems with our CHS exit survey plugin: https://github.com/lookit/lookit-jspsych/issues/138)
**Other**
- Add unit tests for the recently-added view to handle POST requests to update the …
=> IR page fixes; jsPsych updates

exp/views/responses.py
This PR modifies the Video Prefetch queryset to include all of the fields that are needed by the Individual Responses page. I added this Video Prefetch recently but somehow missed the fact that not all necessary fields were included, so the view was producing one additional query per Video to get the non-prefetched fields. 
Tested on Study 374 from staging. 
**Before (develop branch)**
Page load time: 3.61 seconds
Number of queries: 342, including 330 similar (these are the separate repeated queries for each video because some fields were left out of the prefetch)
**After (this branch)**
Page load time: 1.02 seconds
Number of queries: 12, including 2 duplicates
Note that there are still two duplicate queries happening with this view. It's not immediately clear to me where these are coming …
=> Individual Responses page: improve video prefetch queryset

pyproject.toml, uv.lock
This PR makes a few changes that fix some errors that I get on `develop` when I run `uv sync` (errors pasted below). 
The first error was about being unable to build the `gevent` package (pinned version 21.12.0) because of incompatibility with Cython (not listed/pinned). I tried downgrading my Cython version, but that didn't fix it. Upgrading my `gevent` version to 23.9.1 did fix the problem, but I also had to upgrade `greenlet` to 2.0.0.
The second error was related to setuptools trying to treat all top-level directories as Python packages. This just required adding `tool.setuptools.packages.find` to `pyproject.toml` with a list of the top-level directories that are actually Python packages.
- Update `gevent` to 23.9.1 and `greenlet` to 2.0.0.
- Add `setuptools.packages.find` with the …
=> Possible fix for `uv` build error

pyproject.toml, uv.lock
This PR bumps `greenlet` to version 3.0.3. This change allows the use of a precompiled wheel for newer versions of macOS like Sonoma, which @deirdre-k is on.
@deirdre-k and I tried the current `develop` version on her system (macOS Sonoma, M1) and we found that `greenlet` 2.0.0 would not build and there was no precompiled wheel available for her system. Updating `greenlet` to 3.0.3 fixed the problem while maintaining compatibility with the rest of our stack and other developers' systems (macOS Ventura, M1/M2).
Here's a summary of the compatibility for the change here and with the `gevent` update from #1562.
- greenlet 3.0.3
- supports Python 3.7–3.12
- stable release
- gevent 23.9.1 
- supports Python 3.7–3.12
- stable release
- compatible with greenlet v3 (requires greenlet>=2.0.0, but …
=> Update greenlet to 3.0.3

pyproject.toml, uv.lock
This reverts commit 84437c506508742454e1864cc2e673ce43070d24.
The staging server is broken (500 error) following #1564, so this PR reverts that change.
=> Revert "update greenlet to 3.0.3 (#1564)"

.circleci/config.yml, accounts/__init__.py, accounts/admin.py, api/permissions.py, api/urls.py, exp/admin.py, exp/views/lab.py, exp/views/video.py, project/fields/datetime_aware_jsonfield.py, project/settings.py, project/urls.py, pyproject.toml, uv.lock
This PR move Django to version 4.0
Changes:
- Celery-Beat's and Bitfield's version was also incremented.
- "Urls" was replaced with "re_path".
- For forms with JSON, there's a built in JSON field now.
- Postgres version needs to be higher then 10.
=> Django 4.0

.github/dependabot.yml
Let Dependabot know that we're using UV as our package manager.
=> Set Dependabot's ecosystem to UV

studies/models.py
This PR fixes the following error on `develop`/staging: `type object 'datetime.timezone' has no attribute 'now'`. I'm not sure but I'm guessing this came up because of the `datetime` package updates included in our Python version updates and the `pytz`-> `zoneinfo` change.
This PR fixes the problem by using `timezone.now` from `django.utils` instead of `datetime`. There are other ways to fix this, but this approach is consistent with our other timezone-aware timestamps in `studies/tasks.py` and a few other test and migration files.
This change affects the following:
- Study state changes (e.g. submit, approve, etc.) 
- `days_submitted` study property, which is shown at `exp/studies/submitted/`
Study state change error:
Submitted study list page load error:
Study state change is …
=> Fix `'datetime.timezone' has no attribute 'now'`

studies/experiment_builder.py
Fixes #1588
Following some package updates, the EFP builds have started failing. Specifically, the 'get_container_directories' step fails with a type error: "join() argument must be str, bytes, or os.PathLike object, not 'UUID'". It seems that `os.path.join` used to coerce non-strings into strings, and does not do that anymore, so we need to explicitly convert any non-string arguments to strings. 
I had a look through the other places where we use `os.path.join` and couldn't see other cases that look like they'll produce the same error.
=> Fix EFP build error

studies/templates/studies/_image_display.html, studies/templates/studies/_study_fields.html, web/templates/web/studies-history.html, web/templates/web/studies-list.html, web/templates/web/study-detail.html
Some images aren't loading on CHS.  These image names are hard-coded in the database with mixed casing.  Google thinks they're all lowercase.  I am unsure of what changed, but this PR will get us back up and running.   
When study ads are updated, the study image is checked for size.  If the image cannot be found, the site will respond with a "file not found" error.  This is why some people are unable to update their studies.
=> Where image name is hardcoded in the database, we force it to lower case

project/settings.py, project/storages.py
Filename were lowercase but the collision hash was not.  Also fixed BASE_URL having too much ending slash in some cases.
=> Lower case file name

studies/experiment_builder.py
This PR adds some additional logging to the EFP build/deploy process to help us figure out why the study files are not saving to GCS.
=> Add debug logging to locate EFP build/deploy failure

exp/tests/test_contact_views.py, exp/views/contact.py, studies/forms.py, studies/templates/studies/options/recipients.html
Fixes #1618
This PR fixes a problem with the Contact Participants page "recipients" drop-down choices. The participant choices are rendering incorrectly and it is not possible to select them, which means that researchers cannot send messages. 
The PR restructures the choices and data that we use for the email/message "recipients" field on the Contact Participants page. We used to use a nested tuple for each participant/recipient option, where the first element was the UUID and the second contained all of the other info we needed to create the dropdown option element. However, after our package updates, this nested tuple structure is being treated as a set of _grouped_ choices, where the first element is the group name and the second contains the choices in that group (see #1618). Because …
=> Fix "recipients" dropdown on contact participants page

exp/tests/test_contact_views.py, exp/views/contact.py, project/settings.py, project/storages.py, project/urls.py, pyproject.toml, studies/experiment_builder.py, studies/forms.py, studies/helpers.py, studies/templates/studies/_image_display.html, studies/templates/studies/_study_fields.html, studies/templates/studies/options/recipients.html, uv.lock, web/templates/web/studies-history.html, web/templates/web/studies-list.html, web/templates/web/study-detail.html
This PR fixes some issues that came up after a production release containing package updates (https://github.com/lookit/lookit-api/pull/1585).
- Updates `django-storages` settings and our custom storages classes for GCP storage and file paths/URLs. This affects static files, user media (e.g. study images), and built EFP experiment files. This should fix #1615.
- Media files will now always be converted to lowercase before being saved to the database and GCP. 
- Static files keep their original case, because some are generated from packages and we do not have control over them.
- Reverts the temporary fix to image file names in template files (no longer needed).
- Fixes the problem with selecting recipients for new messages on the contact participants (#1618 , #1626)
- Adds a log message …
=> Some fixes into Production

exp/views/video.py, studies/models.py
Fixes #1640
This PR fixes an issue with the pipe webhook returning 500 errors. 
In the `RenameVideoView` API endpoint (`exp/views/video.py`) that we provide to Pipe:
- Get the POST payload from `request.POST` instead of `request.body`, since the former provides the data as a dictionary so no further parsing/conversion is needed.
- Remove the bytes to ints conversion, the use of `urlib.parse.parse_qs`, and the `[0]` indexing on the result because these no longer seem necessary
- 
```python
rawbody = list(request.body)  # bytes to ints
postbody = urllib.parse.parse_qs(
bytes(rawbody).decode("utf-8")
)  # NOW parse the request string
...
message = thisURL + postbody["payload"][0]
```
In the `Video` class method `from_pipe_payload` (`studies/models.py`):
- Instead of specifying a UTC timezone …
=> Fix pipe webhook

develop_test_payloads.csv, studies/management/commands/add_pipe_video_objects_without_S3.py
This PR adds a management command to the 'studies' app. This script only runs when called manually via `manage.py`, and it must be given a CSV file that contains the exported Pipe recordings for processing. The CSV should be located at the project root and deleted after processing.
This can be used to add Pipe videos to the database while bypassing the AWS S3 actions (renaming the video with the Pipe name to our custom name). This is useful for adding Pipe videos to the database when the Pipe webhook processing failed _after_ the S3 naming step (which means that re-running the webhook no longer works because the file with the original Pipe name no longer exists in S3).
Here's how to run the command from docker:
```
docker-compose exec web uv run ./manage.py …
```
=> Add pipe video processing command

studies/forms.py, uv.lock
Fixes #1667
This PR adds the square image dimensions check back into the study form. If the image is not square, the form will not save and the user will remain on the form page with a banner message about the study image dimensions needing to be square. 
This PR also includes some changes to uv.lock that were made after I built the site with the package updates that were recently merged: #1663, #1660
=> Study image square check

studies/tasks.py, studies/templates/studies/study_attachments.html
The temporary directory will not be created in the scratch directory.  Reverting changes to support release to production. 
This reverts commit ba666ac98986341afd50ffb2908725c07ea535c5.
=> Revert "Batch video download (#1675)"

web/templatetags/web_extras.py
Fixes #1664 
As of Django 4.1, the logout action must come from a POST request rather than GET. This PR modifies our `nav_link` template tag so that, when the URL is `/logout/`, we generate the necessary form with `method=post` rather than a simple ink to `/logout/`. 
In order to access the CSRF token, I had to edit both the `nav_link` and `dropdown_item` template tags so that they receive the context and can access the CSRF token from there.
There are lot of different solutions to this problem. I decided to extend our existing template tags for nav items so that they handle logout because I wanted to keep our HTML classes and related logic in one place. I'm open to other approaches and suggestions for improvement!
=> Convert logout request from GET to POST

pyproject.toml, studies/tasks.py, uv.lock
This PR is an attempt to help with #1727 (but should not automatically close that issue).
This is to see whether we can use `stream_zip` to stream files directly into a zip on GCS, rather than storing a temp file. Even though our temp file is stored in the GCS fuse mount rather than in the container, this solution might help prevent the constant RAM usage increase by preventing layered caching from the fuse mount.
=> Use stream_zip for 'download all videos' task

studies/tasks.py
This is another change related to switching to stream-zip to address #1727. This fixes an error in #1737 - the compression argument should have been in the file-specific arguments rather than in the global stream_zip call.
=> Download all videos task: fix incorrect arg in stream_zip

studies/tasks.py
Another iteration on #1737. This time I'm fixing the wrong use of `datetime.now`.
=> Video downloads task: fix datetime.now not found error

studies/tasks.py
This PR adds the following info to the logs at the start of the video zip task:
- study UUID
- requesting user UUID
- consent only (T/F)
This info will be useful for handling potential issues with long-running video zip tasks.
=> Add log for video zip task: study, user, consent_only

api/tests/test_responses.py, studies/serializers.py
Partially addresses [#170](https://github.com/lookit/lookit-jspsych/issues/170)
This PR modifies the response API so that it computes the response object's `sequence` value when:
- the response is for a jsPsych study, and
- the response object already exists (partial/PATCH update) 
It does not affect response handling for EFP or external studies. It also does not affect the creation of new jsPsych response objects.
This is to address a problem with missing and out-of-sync data for jsPsych study responses. This was due to retrieving the previously-saved values (for both `exp_data` and `sequence`) and then appending new data to those values, which was not robust to intermittent failed API requests. The `exp_data` can just be re-sent in full on each update. However, there is no ground-truth …
=> compute frame/trial `sequence` for jsPsych responses
